# Generated by Django 5.2.4 on 2025-08-17 13:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['region__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Région')),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Code unique d'identification (ex: PG001, PS001)", max_length=10, unique=True, verbose_name='Code du poste')),
                ('nom', models.CharField(help_text='Nom complet du poste (ex: Péage de Douala-Nord)', max_length=100, verbose_name='Nom du poste')),
                ('type', models.CharField(choices=[('peage', 'Poste de Péage'), ('pesage', 'Poste de Pesage')], default='peage', max_length=10, verbose_name='Type de poste')),
                ('axe_routier', models.CharField(blank=True, help_text='Axe routier où se situe le poste (ex: Yaoundé-Douala, Douala-Bafoussam)', max_length=100, verbose_name='Axe routier')),
                ('latitude', models.FloatField(blank=True, help_text='Coordonnée GPS latitude', null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, help_text='Coordonnée GPS longitude', null=True, verbose_name='Longitude')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du poste et de sa situation', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Le poste est-il en service ?', verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.departement', verbose_name='Département')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.region', verbose_name='Région')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['region', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='UtilisateurSUPPER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text="Matricule unique de l'agent (ex: INV001, ADM001)", max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Format: 2-4 lettres + 3-4 chiffres (ex: INV001)', regex='^[A-Z]{2,4}[0-9]{3,4}$')], verbose_name='Matricule')),
                ('nom_complet', models.CharField(help_text="Nom et prénom(s) de l'agent", max_length=100, verbose_name='Nom complet')),
                ('telephone', models.CharField(help_text='Numéro de téléphone camerounais', max_length=15, validators=[django.core.validators.RegexValidator(message='Format: +237XXXXXXXXX ou XXXXXXXXX (Cameroun)', regex='^(\\+237)?[0-9]{8,9}$')], verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(blank=True, help_text='Email optionnel pour la réinitialisation de mot de passe', max_length=254, null=True, verbose_name='Adresse email')),
                ('habilitation', models.CharField(choices=[('admin_principal', 'Administrateur Principal'), ('chef_peage', 'Chef de Poste Péage'), ('chef_pesage', 'Chef de Poste Pesage'), ('focal_regional', 'Point Focal Régional'), ('caissier', 'Caissier'), ('agent_inventaire', 'Agent Inventaire'), ('chef_service', 'Chef de Service'), ('coord_psrr', 'Coordonnateur PSRR'), ('serv_info', 'Service Informatique'), ('serv_emission', 'Service Émission et Recouvrement'), ('chef_ag', 'Chef Service Affaires Générales'), ('regisseur', 'Régisseur'), ('comptable_mat', 'Comptable Matières'), ('chef_ordre', 'Chef Service Ordre'), ('chef_controle', 'Chef Service Contrôle'), ('imprimerie', 'Imprimerie Nationale')], default='agent_inventaire', help_text="Rôle de l'utilisateur dans le système SUPPER", max_length=30, verbose_name='Habilitation')),
                ('peut_saisir_peage', models.BooleanField(default=False, help_text='Autorisation de créer/modifier les données de péage', verbose_name='Peut saisir données péage')),
                ('peut_saisir_pesage', models.BooleanField(default=False, help_text='Autorisation de créer/modifier les données de pesage', verbose_name='Peut saisir données pesage')),
                ('acces_tous_postes', models.BooleanField(default=False, help_text="Si False, accès limité au poste d'affectation uniquement", verbose_name='Accès à tous les postes')),
                ('voir_recettes_potentielles', models.BooleanField(default=True, help_text='Autorisation de voir les calculs de recettes potentielles', verbose_name='Peut voir recettes potentielles')),
                ('voir_taux_deperdition', models.BooleanField(default=True, help_text='Autorisation de voir les calculs de taux de déperdition', verbose_name='Peut voir taux déperdition')),
                ('voir_statistiques_globales', models.BooleanField(default=False, help_text='Autorisation de voir stats tous postes (admin/service émission)', verbose_name='Peut voir statistiques globales')),
                ('peut_saisir_pour_autres_postes', models.BooleanField(default=False, help_text='Admin peut saisir inventaires/recettes sur tous postes', verbose_name='Peut saisir pour autres postes')),
                ('peut_gerer_peage', models.BooleanField(default=False, verbose_name='Gérer le péage')),
                ('peut_gerer_pesage', models.BooleanField(default=False, verbose_name='Gérer le pesage')),
                ('peut_gerer_personnel', models.BooleanField(default=False, verbose_name='Gérer le personnel')),
                ('peut_gerer_budget', models.BooleanField(default=False, verbose_name='Gérer le budget')),
                ('peut_gerer_inventaire', models.BooleanField(default=False, verbose_name="Gérer l'inventaire")),
                ('peut_gerer_archives', models.BooleanField(default=False, verbose_name='Gérer les archives')),
                ('peut_gerer_stocks_psrr', models.BooleanField(default=False, verbose_name='Gérer les stocks PSRR')),
                ('peut_gerer_stock_info', models.BooleanField(default=False, verbose_name='Gérer le stock informatique')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('cree_par', models.ForeignKey(blank=True, help_text='Administrateur qui a créé ce compte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('poste_affectation', models.ForeignKey(blank=True, help_text="Poste principal où l'agent est affecté", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_affectes', to='accounts.poste', verbose_name="Poste d'affectation")),
            ],
            options={
                'verbose_name': 'Utilisateur SUPPER',
                'verbose_name_plural': 'Utilisateurs SUPPER',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='accounts.region', verbose_name='Région'),
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Description courte de l'action", max_length=100, verbose_name='Action effectuée')),
                ('details', models.TextField(blank=True, help_text="Description détaillée de l'action et données associées", verbose_name='Détails')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, help_text='Informations sur le navigateur utilisé', max_length=500, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Clé de session')),
                ('url_acces', models.CharField(blank=True, help_text="URL de la page où l'action a été effectuée", max_length=500, verbose_name="URL d'accès")),
                ('methode_http', models.CharField(blank=True, help_text='GET, POST, PUT, DELETE, etc.', max_length=10, verbose_name='Méthode HTTP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('duree_execution', models.DurationField(blank=True, help_text="Temps d'exécution de l'action", null=True, verbose_name="Durée d'exécution")),
                ('statut_reponse', models.IntegerField(blank=True, help_text='200, 404, 500, etc.', null=True, verbose_name='Code de statut HTTP')),
                ('succes', models.BooleanField(default=True, help_text="L'action s'est-elle déroulée avec succès ?", verbose_name='Succès')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_journal', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['utilisateur', 'timestamp'], name='accounts_jo_utilisa_2d3ca9_idx'), models.Index(fields=['action'], name='accounts_jo_action_824eb2_idx'), models.Index(fields=['succes'], name='accounts_jo_succes_a1a8f8_idx'), models.Index(fields=['-timestamp'], name='accounts_jo_timesta_984bdc_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre court de la notification', max_length=200, verbose_name='Titre')),
                ('message', models.TextField(help_text='Contenu détaillé de la notification', verbose_name='Message')),
                ('type_notification', models.CharField(choices=[('info', 'Information'), ('succes', 'Succès'), ('avertissement', 'Avertissement'), ('erreur', 'Erreur')], default='info', max_length=20, verbose_name='Type de notification')),
                ('lu', models.BooleanField(default=False, help_text='La notification a-t-elle été lue ?', verbose_name='Lu')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['destinataire', 'lu'], name='accounts_no_destina_dfc9ea_idx'), models.Index(fields=['type_notification'], name='accounts_no_type_no_d1b603_idx'), models.Index(fields=['-date_creation'], name='accounts_no_date_cr_316c89_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='utilisateursupper',
            index=models.Index(fields=['username'], name='accounts_ut_usernam_98bc07_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateursupper',
            index=models.Index(fields=['habilitation'], name='accounts_ut_habilit_472af7_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateursupper',
            index=models.Index(fields=['poste_affectation'], name='accounts_ut_poste_a_8c9122_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateursupper',
            index=models.Index(fields=['is_active'], name='accounts_ut_is_acti_77f317_idx'),
        ),
        migrations.AddIndex(
            model_name='poste',
            index=models.Index(fields=['code'], name='accounts_po_code_1cbc06_idx'),
        ),
        migrations.AddIndex(
            model_name='poste',
            index=models.Index(fields=['region', 'type'], name='accounts_po_region__2263f0_idx'),
        ),
        migrations.AddIndex(
            model_name='poste',
            index=models.Index(fields=['is_active'], name='accounts_po_is_acti_7958c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='departement',
            unique_together={('region', 'nom')},
        ),
    ]
