# Generated by Django 5.2.4 on 2025-07-19 22:56

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom complet du poste (ex: Péage de Yaoundé-Nord)', max_length=100, verbose_name='Nom du poste')),
                ('code', models.CharField(help_text='Code unique du poste (ex: YDE-N-01)', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Le code doit contenir 3-15 caractères alphanumériques et tirets', regex='^[A-Z0-9-]{3,15}$')], verbose_name='Code du poste')),
                ('type_poste', models.CharField(choices=[('peage', 'Poste de Péage'), ('pesage', 'Poste de Pesage')], max_length=10, verbose_name='Type de poste')),
                ('localisation', models.CharField(help_text='Adresse ou description précise de la localisation', max_length=200, verbose_name='Localisation')),
                ('region', models.CharField(choices=[('adamaoua', 'Adamaoua'), ('centre', 'Centre'), ('est', 'Est'), ('extreme_nord', 'Extrême-Nord'), ('littoral', 'Littoral'), ('nord', 'Nord'), ('nord_ouest', 'Nord-Ouest'), ('ouest', 'Ouest'), ('sud', 'Sud'), ('sud_ouest', 'Sud-Ouest')], max_length=20, verbose_name='Région administrative')),
                ('departement', models.CharField(help_text='Département dans la région', max_length=100, verbose_name='Département')),
                ('arrondissement', models.CharField(blank=True, help_text='Arrondissement (optionnel)', max_length=100, verbose_name='Arrondissement')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Coordonnée GPS latitude', max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Coordonnée GPS longitude', max_digits=10, null=True, verbose_name='Longitude')),
                ('actif', models.BooleanField(default=True, help_text='Indique si le poste est en service', verbose_name='Poste actif')),
                ('date_ouverture', models.DateField(blank=True, help_text='Date de mise en service du poste', null=True, verbose_name="Date d'ouverture")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création dans le système')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('observations', models.TextField(blank=True, help_text='Notes ou observations particulières sur le poste', verbose_name='Observations')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['region', 'nom'],
                'indexes': [models.Index(fields=['code'], name='accounts_po_code_1cbc06_idx'), models.Index(fields=['region', 'type_poste'], name='accounts_po_region_cfe0c6_idx'), models.Index(fields=['actif'], name='accounts_po_actif_9d25c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='UtilisateurSUPPER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text="Matricule unique de l'agent (identifiant de connexion)", max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Le matricule doit contenir 6-20 caractères alphanumériques majuscules', regex='^[A-Z0-9]{6,20}$')], verbose_name='Matricule')),
                ('nom_complet', models.CharField(help_text="Nom et prénom(s) complets de l'agent", max_length=150, verbose_name='Nom complet')),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Format: +237XXXXXXXXX ou XXXXXXXXX (Cameroun)', regex='^\\+?237?[0-9]{8,9}$')], verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(blank=True, help_text='Email optionnel pour la réinitialisation de mot de passe', max_length=254, null=True, verbose_name='Adresse email')),
                ('habilitation', models.CharField(choices=[('admin_principal', 'Administrateur Principal'), ('chef_peage', 'Chef de Poste Péage'), ('chef_pesage', 'Chef de Poste Pesage'), ('focal_regional', 'Point Focal Régional'), ('caissier', 'Caissier'), ('agent_inventaire', 'Agent Inventaire'), ('chef_service', 'Chef de Service'), ('coord_psrr', 'Coordonnateur PSRR'), ('serv_info', 'Service Informatique'), ('serv_emission', 'Service Émission et Recouvrement'), ('chef_ag', 'Chef Service Affaires Générales'), ('regisseur', 'Régisseur'), ('comptable_mat', 'Comptable Matières'), ('chef_ordre', 'Chef Service Ordre'), ('chef_controle', 'Chef Service Contrôle'), ('imprimerie', 'Imprimerie Nationale')], default='agent_inventaire', help_text="Rôle de l'utilisateur dans le système SUPPER", max_length=30, verbose_name='Habilitation')),
                ('peut_saisir_peage', models.BooleanField(default=False, help_text='Autorisation de créer/modifier les données de péage', verbose_name='Peut saisir données péage')),
                ('peut_saisir_pesage', models.BooleanField(default=False, help_text='Autorisation de créer/modifier les données de pesage', verbose_name='Peut saisir données pesage')),
                ('acces_tous_postes', models.BooleanField(default=False, help_text="Si False, accès limité au poste d'affectation uniquement", verbose_name='Accès à tous les postes')),
                ('peut_gerer_peage', models.BooleanField(default=False, verbose_name='Gérer le péage')),
                ('peut_gerer_pesage', models.BooleanField(default=False, verbose_name='Gérer le pesage')),
                ('peut_gerer_personnel', models.BooleanField(default=False, verbose_name='Gérer le personnel')),
                ('peut_gerer_budget', models.BooleanField(default=False, verbose_name='Gérer le budget')),
                ('peut_gerer_inventaire', models.BooleanField(default=True, verbose_name="Gérer l'inventaire")),
                ('peut_gerer_archives', models.BooleanField(default=False, verbose_name='Gérer les archives')),
                ('peut_gerer_stocks_psrr', models.BooleanField(default=False, verbose_name='Gérer les stocks PSRR')),
                ('peut_gerer_stock_info', models.BooleanField(default=False, verbose_name='Gérer le stock informatique')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création du compte')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('photo_profil', models.ImageField(blank=True, help_text='Photo optionnelle pour le profil utilisateur', null=True, upload_to='photos_profil/', verbose_name='Photo de profil')),
                ('commentaires', models.TextField(blank=True, help_text='Notes ou commentaires sur cet utilisateur', verbose_name='Commentaires')),
                ('cree_par', models.ForeignKey(blank=True, help_text='Administrateur qui a créé ce compte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('poste_affectation', models.ForeignKey(blank=True, help_text="Poste principal où l'agent est affecté", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_affectes', to='accounts.poste', verbose_name="Poste d'affectation")),
            ],
            options={
                'verbose_name': 'Utilisateur SUPPER',
                'verbose_name_plural': 'Utilisateurs SUPPER',
                'ordering': ['nom_complet'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Description courte de l'action", max_length=100, verbose_name='Action effectuée')),
                ('details', models.TextField(blank=True, help_text="Description détaillée de l'action et données associées", verbose_name='Détails')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, help_text='Informations sur le navigateur utilisé', max_length=500, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Clé de session')),
                ('url_acces', models.CharField(blank=True, help_text="URL de la page où l'action a été effectuée", max_length=500, verbose_name="URL d'accès")),
                ('methode_http', models.CharField(blank=True, help_text='GET, POST, PUT, DELETE, etc.', max_length=10, verbose_name='Méthode HTTP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('duree_execution', models.DurationField(blank=True, help_text="Temps d'exécution de l'action", null=True, verbose_name="Durée d'exécution")),
                ('statut_reponse', models.IntegerField(blank=True, help_text='200, 404, 500, etc.', null=True, verbose_name='Code de statut HTTP')),
                ('succes', models.BooleanField(default=True, help_text="Indique si l'action s'est déroulée avec succès", verbose_name='Action réussie')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_journal', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Entrée journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['utilisateur', '-timestamp'], name='accounts_jo_utilisa_62f30a_idx'), models.Index(fields=['action'], name='accounts_jo_action_824eb2_idx'), models.Index(fields=['-timestamp'], name='accounts_jo_timesta_984bdc_idx'), models.Index(fields=['succes'], name='accounts_jo_succes_a1a8f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la notification')),
                ('message', models.TextField(verbose_name='Message')),
                ('type_notification', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('success', 'Succès'), ('system', 'Système')], default='info', max_length=20, verbose_name='Type de notification')),
                ('lue', models.BooleanField(default=False, verbose_name='Notification lue')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['destinataire', '-date_creation'], name='accounts_no_destina_c85f05_idx'), models.Index(fields=['lue'], name='accounts_no_lue_f649a9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='utilisateursupper',
            index=models.Index(fields=['username'], name='accounts_ut_usernam_98bc07_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateursupper',
            index=models.Index(fields=['habilitation'], name='accounts_ut_habilit_472af7_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateursupper',
            index=models.Index(fields=['poste_affectation'], name='accounts_ut_poste_a_8c9122_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateursupper',
            index=models.Index(fields=['is_active'], name='accounts_ut_is_acti_77f317_idx'),
        ),
    ]
