# Generated by Django 5.2.4 on 2025-07-21 08:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalaudit',
            options={'ordering': ['-timestamp'], 'verbose_name': "Journal d'audit", 'verbose_name_plural': "Journal d'audit"},
        ),
        migrations.RemoveIndex(
            model_name='journalaudit',
            name='accounts_jo_utilisa_62f30a_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationutilisateur',
            name='accounts_no_destina_c85f05_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationutilisateur',
            name='accounts_no_lue_f649a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='poste',
            name='accounts_po_region_cfe0c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='poste',
            name='accounts_po_actif_9d25c1_idx',
        ),
        migrations.RemoveField(
            model_name='notificationutilisateur',
            name='expediteur',
        ),
        migrations.RemoveField(
            model_name='notificationutilisateur',
            name='lue',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='date_ouverture',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='localisation',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='type_poste',
        ),
        migrations.RemoveField(
            model_name='utilisateursupper',
            name='commentaires',
        ),
        migrations.RemoveField(
            model_name='utilisateursupper',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='utilisateursupper',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='utilisateursupper',
            name='photo_profil',
        ),
        migrations.AddField(
            model_name='notificationutilisateur',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='notificationutilisateur',
            name='lu',
            field=models.BooleanField(default=False, help_text='La notification a-t-elle été lue ?', verbose_name='Lu'),
        ),
        migrations.AddField(
            model_name='poste',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée du poste et de sa situation', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='poste',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Le poste est-il en service ?', verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='poste',
            name='type',
            field=models.CharField(choices=[('peage', 'Poste de Péage'), ('pesage', 'Poste de Pesage')], default='peage', max_length=10, verbose_name='Type de poste'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_saisir_pour_autres_postes',
            field=models.BooleanField(default=False, help_text='Admin peut saisir inventaires/recettes sur tous postes', verbose_name='Peut saisir pour autres postes'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='voir_recettes_potentielles',
            field=models.BooleanField(default=True, help_text='Autorisation de voir les calculs de recettes potentielles', verbose_name='Peut voir recettes potentielles'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='voir_statistiques_globales',
            field=models.BooleanField(default=False, help_text='Autorisation de voir stats tous postes (admin/service émission)', verbose_name='Peut voir statistiques globales'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='voir_taux_deperdition',
            field=models.BooleanField(default=True, help_text='Autorisation de voir les calculs de taux de déperdition', verbose_name='Peut voir taux déperdition'),
        ),
        migrations.AlterField(
            model_name='journalaudit',
            name='succes',
            field=models.BooleanField(default=True, help_text="L'action s'est-elle déroulée avec succès ?", verbose_name='Succès'),
        ),
        migrations.AlterField(
            model_name='notificationutilisateur',
            name='message',
            field=models.TextField(help_text='Contenu détaillé de la notification', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notificationutilisateur',
            name='titre',
            field=models.CharField(help_text='Titre court de la notification', max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='notificationutilisateur',
            name='type_notification',
            field=models.CharField(choices=[('info', 'Information'), ('succes', 'Succès'), ('avertissement', 'Avertissement'), ('erreur', 'Erreur')], default='info', max_length=20, verbose_name='Type de notification'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='arrondissement',
            field=models.CharField(blank=True, max_length=50, verbose_name='Arrondissement'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='code',
            field=models.CharField(help_text="Code unique d'identification (ex: PG001, PS001)", max_length=10, unique=True, verbose_name='Code du poste'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='date_modification',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='departement',
            field=models.CharField(blank=True, max_length=50, verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Coordonnée GPS latitude', null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Coordonnée GPS longitude', null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='nom',
            field=models.CharField(help_text='Nom complet du poste (ex: Péage de Douala-Nord)', max_length=100, verbose_name='Nom du poste'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='region',
            field=models.CharField(help_text='Région administrative du Cameroun', max_length=50, verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='utilisateursupper',
            name='cree_par',
            field=models.ForeignKey(blank=True, help_text='Administrateur qui a créé ce compte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='utilisateursupper',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='utilisateursupper',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='utilisateursupper',
            name='nom_complet',
            field=models.CharField(help_text="Nom et prénom(s) de l'agent", max_length=100, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='utilisateursupper',
            name='peut_gerer_inventaire',
            field=models.BooleanField(default=False, verbose_name="Gérer l'inventaire"),
        ),
        migrations.AlterField(
            model_name='utilisateursupper',
            name='telephone',
            field=models.CharField(help_text='Numéro de téléphone camerounais', max_length=15, validators=[django.core.validators.RegexValidator(message='Format: +237XXXXXXXXX ou XXXXXXXXX (Cameroun)', regex='^(\\+237)?[0-9]{8,9}$')], verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='utilisateursupper',
            name='username',
            field=models.CharField(help_text="Matricule unique de l'agent (ex: INV001, ADM001)", max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Format: 2-4 lettres + 3-4 chiffres (ex: INV001)', regex='^[A-Z]{2,4}[0-9]{3,4}$')], verbose_name='Matricule'),
        ),
        migrations.AddIndex(
            model_name='journalaudit',
            index=models.Index(fields=['utilisateur', 'timestamp'], name='accounts_jo_utilisa_2d3ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationutilisateur',
            index=models.Index(fields=['destinataire', 'lu'], name='accounts_no_destina_dfc9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationutilisateur',
            index=models.Index(fields=['type_notification'], name='accounts_no_type_no_d1b603_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationutilisateur',
            index=models.Index(fields=['-date_creation'], name='accounts_no_date_cr_316c89_idx'),
        ),
        migrations.AddIndex(
            model_name='poste',
            index=models.Index(fields=['region', 'type'], name='accounts_po_region_dfd1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='poste',
            index=models.Index(fields=['is_active'], name='accounts_po_is_acti_7958c8_idx'),
        ),
    ]
