# Generated by Django 5.2.4 on 2025-07-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_journalaudit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='arrondissement',
        ),
        migrations.AddField(
            model_name='poste',
            name='axe_routier',
            field=models.CharField(blank=True, help_text='Axe routier où se situe le poste (ex: Yaoundé-Douala, Douala-Bafoussam)', max_length=100, verbose_name='Axe routier'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
    ]
