# Generated by Django 5.2.4 on 2025-09-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_utilisateursupper_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='objectif_annuel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Objectif de recettes annuelles pour ce poste', max_digits=15, null=True, verbose_name='Objectif annuel (FCFA)'),
        ),
    ]
