# Generated by Django 5.2.4 on 2025-09-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_poste_objectif_annuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='objectif_annuel',
        ),
    ]
