# Generated by Django 5.2.4 on 2025-11-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_poste_objectif_annuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='nouveau',
            field=models.BooleanField(default=False, help_text="Cocher si c'est un nouveau poste pour l'année en cours", verbose_name='Nouveau poste'),
        ),
    ]
