# Generated by Django 5.2.4 on 2025-12-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_utilisateursupper_habilitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateursupper',
            name='habilitation',
            field=models.CharField(choices=[('admin_principal', 'Administrateur Principal'), ('chef_peage', 'Chef de Poste Péage'), ('chef_station_pesage', 'Chef de Station Pesage'), ('chef_equipe_pesage', "Chef d'Équipe Pesage"), ('regisseur_pesage', 'Régisseur Pesage'), ('focal_regional', 'Point Focal Régional'), ('agent_inventaire', 'Agent Inventaire'), ('chef_service', 'Chef de Service'), ('coord_psrr', 'Coordonnateur PSRR'), ('serv_info', 'Service Informatique'), ('serv_emission', 'Service Émission et Recouvrement'), ('chef_ag', 'Chef Service Affaires Générales'), ('regisseur', 'Régisseur'), ('comptable_mat', 'Comptable Matières'), ('chef_ordre', 'Chef Service Ordre'), ('chef_controle', 'Chef Service Contrôle'), ('imprimerie', 'Imprimerie Nationale')], default='agent_inventaire', help_text="Rôle de l'utilisateur dans le système SUPPER", max_length=30, verbose_name='Habilitation'),
        ),
    ]
