# Generated by Django 5.2.4 on 2025-12-12 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_utilisateursupper_habilitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_ajouter_poste',
            field=models.BooleanField(default=False, verbose_name='Ajouter un poste'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_authentifier_document',
            field=models.BooleanField(default=False, verbose_name='Authentifier document'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_charger_stock_peage',
            field=models.BooleanField(default=False, verbose_name='Charger stock péage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_comptabiliser_quittances_peage',
            field=models.BooleanField(default=False, verbose_name='Comptabiliser quittances péage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_comptabiliser_quittances_pesage',
            field=models.BooleanField(default=False, verbose_name='Comptabiliser quittances pesage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_creer_poste_masse',
            field=models.BooleanField(default=False, verbose_name='Créer postes en masse'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_creer_utilisateur',
            field=models.BooleanField(default=False, verbose_name='Créer utilisateur'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_desactiver_programmation',
            field=models.BooleanField(default=False, verbose_name='Désactiver programmation'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_gerer_postes',
            field=models.BooleanField(default=False, verbose_name='Gérer les postes'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_gerer_utilisateurs',
            field=models.BooleanField(default=False, verbose_name='Gérer utilisateurs'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_importer_recettes_peage',
            field=models.BooleanField(default=False, verbose_name='Importer recettes péage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_lister_amendes',
            field=models.BooleanField(default=False, verbose_name='Lister amendes'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_parametrage_global',
            field=models.BooleanField(default=False, verbose_name='Paramétrage global'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_programmer_inventaire',
            field=models.BooleanField(default=False, verbose_name='Programmer inventaire'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_saisir_amende',
            field=models.BooleanField(default=False, verbose_name='Saisir amende'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_saisir_inventaire_admin',
            field=models.BooleanField(default=False, verbose_name='Saisir inventaire administratif'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_saisir_inventaire_normal',
            field=models.BooleanField(default=False, verbose_name='Saisir inventaire normal'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_saisir_pesee_jour',
            field=models.BooleanField(default=False, verbose_name='Saisir pesée du jour'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_saisir_quittance_peage',
            field=models.BooleanField(default=False, verbose_name='Saisir quittance péage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_saisir_quittance_pesage',
            field=models.BooleanField(default=False, verbose_name='Saisir quittance pesage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_saisir_recette_peage',
            field=models.BooleanField(default=False, verbose_name='Saisir recette péage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_simuler_commandes_peage',
            field=models.BooleanField(default=False, verbose_name='Simuler commandes péage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_transferer_stock_peage',
            field=models.BooleanField(default=False, verbose_name='Transférer stock péage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_valider_paiement_amende',
            field=models.BooleanField(default=False, verbose_name='Valider paiement amende'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_bordereaux_peage',
            field=models.BooleanField(default=False, verbose_name='Voir bordereaux péage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_classement_agents_inventaire',
            field=models.BooleanField(default=False, verbose_name='Voir classement agents inventaire'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_classement_peage_deperdition',
            field=models.BooleanField(default=False, verbose_name='Voir classement péage déperdition'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_classement_peage_rendement',
            field=models.BooleanField(default=False, verbose_name='Voir classement péage rendement'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_classement_station_pesage',
            field=models.BooleanField(default=False, verbose_name='Voir classement station pesage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_compte_emploi',
            field=models.BooleanField(default=False, verbose_name="Voir compte d'emploi"),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_evolution_peage',
            field=models.BooleanField(default=False, verbose_name='Voir évolution péage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_historique_pesees',
            field=models.BooleanField(default=False, verbose_name='Voir historique pesées'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_historique_stock_peage',
            field=models.BooleanField(default=False, verbose_name='Voir historique stock péage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_historique_vehicule_pesage',
            field=models.BooleanField(default=False, verbose_name='Voir historique véhicule pesage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_journal_audit',
            field=models.BooleanField(default=False, verbose_name='Voir journal audit'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_jours_impertinents',
            field=models.BooleanField(default=False, verbose_name='Voir jours impertinents'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_liste_inventaires',
            field=models.BooleanField(default=False, verbose_name='Voir liste inventaires'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_liste_inventaires_admin',
            field=models.BooleanField(default=False, verbose_name='Voir liste inventaires admin'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_liste_quittancements_pesage',
            field=models.BooleanField(default=False, verbose_name='Voir liste quittancements pesage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_liste_quittances_peage',
            field=models.BooleanField(default=False, verbose_name='Voir liste quittances péage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_liste_recettes_peage',
            field=models.BooleanField(default=False, verbose_name='Voir liste recettes péage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_liste_stocks_peage',
            field=models.BooleanField(default=False, verbose_name='Voir liste stocks péage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_mon_stock_peage',
            field=models.BooleanField(default=False, verbose_name='Voir mon stock péage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_objectifs_peage',
            field=models.BooleanField(default=False, verbose_name='Voir objectifs péage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_objectifs_pesage',
            field=models.BooleanField(default=False, verbose_name='Voir objectifs pesage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_programmation_active',
            field=models.BooleanField(default=False, verbose_name='Voir programmation active'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_programmation_desactivee',
            field=models.BooleanField(default=False, verbose_name='Voir programmations désactivées'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_pv_confrontation',
            field=models.BooleanField(default=False, verbose_name='Voir PV confrontation'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_rapport_inventaires',
            field=models.BooleanField(default=False, verbose_name='Voir rapport inventaires'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_rapports_defaillants_peage',
            field=models.BooleanField(default=False, verbose_name='Voir rapports défaillants péage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_rapports_defaillants_pesage',
            field=models.BooleanField(default=False, verbose_name='Voir rapports défaillants pesage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_recettes_pesage',
            field=models.BooleanField(default=False, verbose_name='Voir recettes pesage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_stats_deperdition',
            field=models.BooleanField(default=False, verbose_name='Voir stats déperdition'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_stats_pesage',
            field=models.BooleanField(default=False, verbose_name='Voir stats pesage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_stats_recettes_peage',
            field=models.BooleanField(default=False, verbose_name='Voir stats recettes péage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_stock_date_peage',
            field=models.BooleanField(default=False, verbose_name='Voir stock à date péage'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_tous_postes',
            field=models.BooleanField(default=False, verbose_name='Voir tous les postes'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='peut_voir_tracabilite_tickets',
            field=models.BooleanField(default=False, verbose_name='Voir traçabilité tickets'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='axe_routier',
            field=models.CharField(blank=True, help_text='Axe routier où se situe le poste (ex: Yaoundé-Douala)', max_length=100, verbose_name='Axe routier'),
        ),
        migrations.AlterField(
            model_name='utilisateursupper',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='utilisateursupper',
            name='habilitation',
            field=models.CharField(choices=[('admin_principal', 'Administrateur Principal'), ('coord_psrr', 'Coordonnateur PSRR'), ('serv_info', 'Service Informatique'), ('serv_emission', 'Service Émissions et Recouvrement'), ('chef_ag', 'Service des Affaires Générales'), ('serv_controle', 'Service Contrôle et Validation'), ('serv_ordre', 'Service Ordre/Secrétariat'), ('imprimerie', 'Imprimerie Nationale'), ('cisop_peage', 'CISOP Péage'), ('cisop_pesage', 'CISOP Pesage'), ('chef_peage', 'Chef de Poste Péage'), ('agent_inventaire', 'Agent Inventaire'), ('chef_station_pesage', 'Chef de Station Pesage'), ('regisseur_pesage', 'Régisseur de Station Pesage'), ('chef_equipe_pesage', "Chef d'Équipe Pesage"), ('focal_regional', 'Point Focal Régional'), ('chef_service', 'Chef de Service'), ('regisseur', 'Régisseur Central'), ('comptable_mat', 'Comptable Matières'), ('chef_ordre', 'Chef Service Ordre'), ('chef_controle', 'Chef Service Contrôle')], default='agent_inventaire', help_text="Rôle de l'utilisateur dans le système SUPPER", max_length=30, verbose_name='Habilitation'),
        ),
        migrations.AlterField(
            model_name='utilisateursupper',
            name='peut_gerer_stock_info',
            field=models.BooleanField(default=False, verbose_name='Gérer le stock info'),
        ),
        migrations.AlterField(
            model_name='utilisateursupper',
            name='peut_saisir_peage',
            field=models.BooleanField(default=False, verbose_name='Peut saisir données péage'),
        ),
        migrations.AlterField(
            model_name='utilisateursupper',
            name='peut_saisir_pesage',
            field=models.BooleanField(default=False, verbose_name='Peut saisir données pesage'),
        ),
        migrations.AlterField(
            model_name='utilisateursupper',
            name='peut_saisir_pour_autres_postes',
            field=models.BooleanField(default=False, verbose_name='Peut saisir pour autres postes'),
        ),
        migrations.AlterField(
            model_name='utilisateursupper',
            name='voir_recettes_potentielles',
            field=models.BooleanField(default=False, verbose_name='Peut voir recettes potentielles'),
        ),
        migrations.AlterField(
            model_name='utilisateursupper',
            name='voir_statistiques_globales',
            field=models.BooleanField(default=False, verbose_name='Peut voir statistiques globales'),
        ),
        migrations.AlterField(
            model_name='utilisateursupper',
            name='voir_taux_deperdition',
            field=models.BooleanField(default=False, verbose_name='Peut voir taux déperdition'),
        ),
    ]
