# Generated by Django 5.2.4 on 2025-12-14 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_utilisateursupper_peut_ajouter_poste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateursupper',
            name='date_personnalisation',
            field=models.DateTimeField(blank=True, help_text='Date de la dernière modification manuelle des permissions', null=True, verbose_name='Date de personnalisation'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='permissions_personnalisees',
            field=models.BooleanField(default=False, help_text='Si True, les permissions ont été modifiées manuellement et ne seront pas écrasées par fix_user_permissions', verbose_name='Permissions personnalisées'),
        ),
        migrations.AddField(
            model_name='utilisateursupper',
            name='personnalise_par',
            field=models.ForeignKey(blank=True, help_text='Administrateur qui a personnalisé les permissions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_personnalises', to=settings.AUTH_USER_MODEL, verbose_name='Personnalisé par'),
        ),
    ]
