# Generated by Django 5.2.4 on 2025-08-09 13:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventaireJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text="Date pour laquelle l'inventaire est effectué", verbose_name="Date de l'inventaire")),
                ('verrouille', models.BooleanField(default=False, help_text="Une fois verrouillé, l'inventaire ne peut plus être modifié", verbose_name='Inventaire verrouillé')),
                ('valide', models.BooleanField(default=False, help_text='Validation par un responsable', verbose_name='Inventaire validé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('total_vehicules', models.IntegerField(default=0, help_text='Somme de tous les véhicules comptés dans les périodes', verbose_name='Total véhicules comptés')),
                ('nombre_periodes_saisies', models.IntegerField(default=0, help_text='Nombre de créneaux horaires avec données', verbose_name='Nombre de périodes saisies')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('observations', models.TextField(blank=True, help_text='Notes particulières sur cet inventaire', verbose_name='Observations')),
                ('agent_saisie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_saisis', to=settings.AUTH_USER_MODEL, verbose_name='Agent de saisie')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='accounts.poste', verbose_name='Poste')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Inventaire journalier',
                'verbose_name_plural': 'Inventaires journaliers',
                'ordering': ['-date', 'poste__nom'],
            },
        ),
        migrations.CreateModel(
            name='DetailInventairePeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('08h-09h', '08h-09h'), ('09h-10h', '09h-10h'), ('10h-11h', '10h-11h'), ('11h-12h', '11h-12h'), ('12h-13h', '12h-13h'), ('13h-14h', '13h-14h'), ('14h-15h', '14h-15h'), ('15h-16h', '15h-16h'), ('16h-17h', '16h-17h'), ('17h-18h', '17h-18h')], max_length=10, verbose_name='Période horaire')),
                ('nombre_vehicules', models.IntegerField(help_text='Nombre de véhicules comptés pendant cette période', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Nombre de véhicules')),
                ('heure_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Heure de saisie')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('observations_periode', models.CharField(blank=True, help_text='Notes sur cette période (incidents, conditions particulières)', max_length=200, verbose_name='Observations')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_periodes', to='inventaire.inventairejournalier', verbose_name='Inventaire')),
            ],
            options={
                'verbose_name': 'Détail inventaire période',
                'verbose_name_plural': 'Détails inventaire par période',
                'ordering': ['periode'],
            },
        ),
        migrations.CreateModel(
            name='RecetteJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de la recette')),
                ('montant_declare', models.DecimalField(decimal_places=2, help_text='Recette déclarée par le chef de poste', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant déclaré (FCFA)')),
                ('recette_potentielle', models.DecimalField(blank=True, decimal_places=2, help_text="Calculée automatiquement à partir de l'inventaire", max_digits=12, null=True, verbose_name='Recette potentielle (FCFA)')),
                ('ecart', models.DecimalField(blank=True, decimal_places=2, help_text='Différence entre recette déclarée et potentielle', max_digits=12, null=True, verbose_name='Écart (FCFA)')),
                ('taux_deperdition', models.DecimalField(blank=True, decimal_places=2, help_text='Taux de déperdition calculé', max_digits=6, null=True, verbose_name='Taux de déperdition (%)')),
                ('verrouille', models.BooleanField(default=False, verbose_name='Recette verrouillée')),
                ('valide', models.BooleanField(default=False, verbose_name='Recette validée')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('observations', models.TextField(blank=True, help_text='Commentaires sur cette recette', verbose_name='Observations')),
                ('chef_poste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recettes_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Chef de poste')),
                ('inventaire_associe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recette', to='inventaire.inventairejournalier', verbose_name='Inventaire associé')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recettes', to='accounts.poste', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Recette journalière',
                'verbose_name_plural': 'Recettes journalières',
                'ordering': ['-date', 'poste__nom'],
            },
        ),
        migrations.CreateModel(
            name='StatistiquesPeriodiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_periode', models.CharField(choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('annuelle', 'Annuelle')], max_length=15, verbose_name='Type de période')),
                ('date_debut', models.DateField(verbose_name='Date de début de période')),
                ('date_fin', models.DateField(verbose_name='Date de fin de période')),
                ('nombre_jours_actifs', models.IntegerField(default=0, verbose_name='Nombre de jours avec données')),
                ('total_recettes_declarees', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Total recettes déclarées')),
                ('total_recettes_potentielles', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Total recettes potentielles')),
                ('taux_deperdition_moyen', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Taux de déperdition moyen (%)')),
                ('nombre_jours_impertinents', models.IntegerField(default=0, verbose_name='Nombre de jours impertinents')),
                ('date_calcul', models.DateTimeField(auto_now=True, verbose_name='Date du calcul')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='accounts.poste', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Statistiques périodiques',
                'verbose_name_plural': 'Statistiques périodiques',
                'ordering': ['-date_debut', 'poste__nom'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date concernée par cette configuration', unique=True, verbose_name='Date')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert pour saisie'), ('ferme', 'Fermé - saisie verrouillée'), ('impertinent', 'Journée impertinente')], default='ouvert', max_length=15, verbose_name='Statut du jour')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('commentaire', models.TextField(blank=True, help_text='Raison de la configuration ou notes particulières', verbose_name='Commentaire')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jours_configures', to=settings.AUTH_USER_MODEL, verbose_name='Configuré par')),
            ],
            options={
                'verbose_name': 'Configuration de jour',
                'verbose_name_plural': 'Configurations de jours',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='inventaire__date_5bc0cd_idx'), models.Index(fields=['statut'], name='inventaire__statut_76426f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inventairejournalier',
            index=models.Index(fields=['poste', '-date'], name='inventaire__poste_i_6f3e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventairejournalier',
            index=models.Index(fields=['date'], name='inventaire__date_c7a3d2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventairejournalier',
            index=models.Index(fields=['agent_saisie'], name='inventaire__agent_s_3f2d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventairejournalier',
            index=models.Index(fields=['verrouille'], name='inventaire__verroui_98fd8d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventairejournalier',
            unique_together={('poste', 'date')},
        ),
        migrations.AddIndex(
            model_name='detailinventaireperiode',
            index=models.Index(fields=['inventaire', 'periode'], name='inventaire__inventa_e949eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detailinventaireperiode',
            unique_together={('inventaire', 'periode')},
        ),
        migrations.AddIndex(
            model_name='recettejournaliere',
            index=models.Index(fields=['poste', '-date'], name='inventaire__poste_i_8f47c9_idx'),
        ),
        migrations.AddIndex(
            model_name='recettejournaliere',
            index=models.Index(fields=['date'], name='inventaire__date_7449b6_idx'),
        ),
        migrations.AddIndex(
            model_name='recettejournaliere',
            index=models.Index(fields=['chef_poste'], name='inventaire__chef_po_46d9ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recettejournaliere',
            unique_together={('poste', 'date')},
        ),
        migrations.AddIndex(
            model_name='statistiquesperiodiques',
            index=models.Index(fields=['poste', 'type_periode', '-date_debut'], name='inventaire__poste_i_e35e3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='statistiquesperiodiques',
            unique_together={('poste', 'type_periode', 'date_debut')},
        ),
    ]
