# Generated by Django 5.2.4 on 2025-09-19 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueAffectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_affectation', models.CharField(choices=[('chef_poste', 'Chef de poste'), ('agent_inventaire', 'Agent inventaire')], max_length=20)),
                ('date_debut', models.DateField(verbose_name="Date de début d'affectation")),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name="Date de fin d'affectation")),
                ('actif', models.BooleanField(default=True, verbose_name='Affectation active')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_affectations', to='accounts.poste')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_affectations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_debut'],
                'indexes': [models.Index(fields=['poste', 'date_debut'], name='inventaire__poste_i_a73c71_idx'), models.Index(fields=['utilisateur', 'actif'], name='inventaire__utilisa_7529f6_idx')],
            },
        ),
    ]
