# Generated by Django 5.2.4 on 2025-08-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventairemensuel',
            name='jours_actifs',
        ),
    ]
