# Generated by Django 5.2.4 on 2025-09-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0002_historiqueaffectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventairejournalier',
            name='type_inventaire',
            field=models.CharField(choices=[('normal', 'Inventaire Normal'), ('administratif', 'Inventaire Administratif')], default='normal', max_length=20, verbose_name="Type d'inventaire"),
        ),
        migrations.AlterField(
            model_name='inventairemensuel',
            name='motif',
            field=models.CharField(choices=[('taux_deperdition', 'Taux de déperdition élevé'), ('risque_baisse', 'Risque de baisse annuel'), ('grand_stock', 'Risque de grand stock'), ('presence_admin', 'Présence administrative')], default='taux_deperdition', max_length=20, verbose_name="Motif de l'inventaire"),
        ),
        migrations.AlterField(
            model_name='programmationinventaire',
            name='motif',
            field=models.CharField(choices=[('taux_deperdition', 'Taux de déperdition élevé'), ('risque_baisse', 'Risque de baisse annuel'), ('grand_stock', 'Risque de grand stock'), ('presence_admin', 'Présence administrative')], default=0, max_length=20, verbose_name="Motif de l'inventaire"),
        ),
    ]
