# Generated by Django 5.2.4 on 2025-08-17 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0002_add_jours_actifs_to_inventaire_mensuel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventairemensuel',
            name='inventaire__annee_90fdc0_idx',
        ),
        migrations.AddField(
            model_name='inventairemensuel',
            name='jours_actifs',
            field=models.JSONField(default=list, help_text='Liste des jours du mois où la saisie est autorisée', verbose_name='Jours actifs'),
        ),
        migrations.AlterField(
            model_name='inventairemensuel',
            name='actif',
            field=models.BooleanField(default=True, help_text='Indique si cet inventaire mensuel est en cours', verbose_name='Inventaire actif'),
        ),
        migrations.AlterField(
            model_name='inventairemensuel',
            name='annee',
            field=models.IntegerField(help_text="Année de l'inventaire", verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='inventairemensuel',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée de cet inventaire mensuel', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='inventairemensuel',
            name='mois',
            field=models.CharField(choices=[('01', 'Janvier'), ('02', 'Février'), ('03', 'Mars'), ('04', 'Avril'), ('05', 'Mai'), ('06', 'Juin'), ('07', 'Juillet'), ('08', 'Août'), ('09', 'Septembre'), ('10', 'Octobre'), ('11', 'Novembre'), ('12', 'Décembre')], max_length=2, verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='inventairemensuel',
            name='titre',
            field=models.CharField(help_text='Titre descriptif pour cet inventaire mensuel', max_length=200, verbose_name="Titre de l'inventaire"),
        ),
        migrations.AddIndex(
            model_name='inventairemensuel',
            index=models.Index(fields=['mois', 'annee'], name='inventaire__mois_80f16b_idx'),
        ),
    ]
