# Generated by Django 5.2.4 on 2025-08-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0003_remove_inventairemensuel_inventaire__annee_90fdc0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventairemensuel',
            name='jours_actifs',
            field=models.TextField(blank=True, default='[]', help_text='Liste des jours du mois (JSON)', verbose_name='Jours actifs'),
        ),
    ]
