# Generated by Django 5.2.4 on 2025-09-26 07:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_utilisateursupper_username'),
        ('inventaire', '0003_inventairejournalier_type_inventaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_monetaire', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Valeur monétaire (FCFA)')),
                ('nombre_tickets', models.IntegerField(default=0, help_text='Calculé automatiquement : valeur / 500', verbose_name='Nombre de tickets')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('poste', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='accounts.poste', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Gestion du stock',
                'verbose_name_plural': 'Gestion des stocks',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('CREDIT', 'Crédit/Approvisionnement'), ('DEBIT', 'Débit/Vente')], max_length=10, verbose_name='Type de mouvement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('nombre_tickets', models.IntegerField(verbose_name='Nombre de tickets')),
                ('stock_avant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Stock avant (FCFA)')),
                ('stock_apres', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Stock après (FCFA)')),
                ('date_mouvement', models.DateTimeField(auto_now_add=True, verbose_name='Date du mouvement')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_stocks', to='accounts.poste', verbose_name='Poste')),
                ('reference_recette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventaire.recettejournaliere', verbose_name='Recette associée')),
            ],
            options={
                'verbose_name': 'Historique stock',
                'verbose_name_plural': 'Historiques stocks',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
