# Generated by Django 5.2.4 on 2025-09-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0004_gestionstock_historiquestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='recettejournaliere',
            name='prolongation_accordee',
            field=models.BooleanField(default=False, help_text='Indique si une prolongation a été accordée pour ce poste', verbose_name='Prolongation accordée'),
        ),
    ]
