# Generated by Django 5.2.4 on 2025-08-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0004_alter_inventairemensuel_jours_actifs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventairemensuel',
            name='jours_actifs',
            field=models.JSONField(blank=True, default=list, help_text='Liste des jours du mois où la saisie est autorisée', verbose_name='Jours actifs'),
        ),
    ]
