# Generated by Django 5.2.4 on 2025-08-17 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventaire', '0005_fix_jours_actifs_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationjour',
            name='permet_saisie_inventaire',
            field=models.BooleanField(default=True, help_text="Autorise la saisie d'inventaires pour cette date", verbose_name='Permet saisie inventaire'),
        ),
        migrations.AddField(
            model_name='configurationjour',
            name='permet_saisie_recette',
            field=models.BooleanField(default=True, help_text='Autorise la saisie de recettes pour cette date', verbose_name='Permet saisie recette'),
        ),
        migrations.AddField(
            model_name='configurationjour',
            name='poste',
            field=models.ForeignKey(blank=True, help_text="Si spécifié, la configuration ne s'applique qu'à ce poste. Si vide, s'applique à tous les postes.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configurations_jours', to='accounts.poste', verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='configurationjour',
            name='date',
            field=models.DateField(help_text='Date concernée par cette configuration', verbose_name='Date'),
        ),
        migrations.AlterUniqueTogether(
            name='configurationjour',
            unique_together={('date', 'poste')},
        ),
        migrations.AddIndex(
            model_name='configurationjour',
            index=models.Index(fields=['poste', 'date'], name='inventaire__poste_i_c1aa75_idx'),
        ),
    ]
