# Generated by Django 5.2.4 on 2025-09-27 18:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_poste_objectif_annuel'),
        ('inventaire', '0005_recettejournaliere_prolongation_accordee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectifAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2099)], verbose_name='Année')),
                ('montant_objectif', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant objectif annuel (FCFA)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectifs_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_annuels', to='accounts.poste', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Objectif annuel',
                'verbose_name_plural': 'Objectifs annuels',
                'ordering': ['-annee', 'poste__nom'],
                'indexes': [models.Index(fields=['poste', '-annee'], name='inventaire__poste_i_80e6c8_idx')],
                'unique_together': {('poste', 'annee')},
            },
        ),
    ]
