# Generated by Django 5.2.4 on 2025-08-17 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventaire', '0006_configurationjour_permet_saisie_inventaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='configurationjour',
            name='inventaire__poste_i_c1aa75_idx',
        ),
        migrations.AlterUniqueTogether(
            name='configurationjour',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='configurationjour',
            constraint=models.UniqueConstraint(fields=('date',), name='unique_date_configuration'),
        ),
    ]
