# Generated by Django 5.2.4 on 2025-10-05 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_poste_objectif_annuel'),
        ('inventaire', '0006_objectifannuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquestock',
            name='type_stock',
            field=models.CharField(blank=True, choices=[('regularisation', 'Régularisation'), ('imprimerie_nationale', 'Imprimerie Nationale')], help_text="Type d'approvisionnement", max_length=30, null=True, verbose_name='Type de stock'),
        ),
        migrations.CreateModel(
            name='ConfigurationPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_postes/', verbose_name='Logo')),
                ('republique_fr', models.CharField(default='RÉPUBLIQUE DU CAMEROUN', max_length=200, verbose_name='République (FR)')),
                ('devise_fr', models.CharField(default='Paix-Travail-Patrie', max_length=200, verbose_name='Devise (FR)')),
                ('ministere_fr', models.CharField(default='MINISTÈRE DES FINANCES', max_length=300, verbose_name='Ministère (FR)')),
                ('direction_fr', models.CharField(default='DIRECTION GÉNÉRALE DES IMPÔTS', max_length=300, verbose_name='Direction (FR)')),
                ('programme_fr', models.CharField(default='PROGRAMME DE SÉCURISATION DES RECETTES ROUTIÈRES', max_length=300, verbose_name='Programme (FR)')),
                ('nom_poste_fr', models.CharField(blank=True, max_length=200, verbose_name='Nom du poste (FR)')),
                ('republique_en', models.CharField(default='REPUBLIC OF CAMEROON', max_length=200, verbose_name='République (EN)')),
                ('devise_en', models.CharField(default='Peace-Work-Fatherland', max_length=200, verbose_name='Devise (EN)')),
                ('ministere_en', models.CharField(default='MINISTRY OF FINANCE', max_length=300, verbose_name='Ministère (EN)')),
                ('direction_en', models.CharField(default='GENERAL DIRECTORATE OF TAXATION', max_length=300, verbose_name='Direction (EN)')),
                ('programme_en', models.CharField(default='REGIONAL TAXATION CENTER OF THE EST', max_length=300, verbose_name='Programme (EN)')),
                ('nom_poste_en', models.CharField(blank=True, max_length=200, verbose_name='Nom du poste (EN)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('poste', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='accounts.poste', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Configuration poste',
                'verbose_name_plural': 'Configurations postes',
            },
        ),
    ]
