# Generated by Django 5.2.4 on 2025-10-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0007_historiquestock_type_stock_configurationposte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationGlobale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('republique_fr', models.CharField(default='RÉPUBLIQUE DU CAMEROUN', max_length=200, verbose_name='République (FR)')),
                ('devise_fr', models.CharField(default='Paix-Travail-Patrie', max_length=200, verbose_name='Devise (FR)')),
                ('ministere_fr', models.CharField(default='MINISTÈRE DES FINANCES', max_length=300, verbose_name='Ministère (FR)')),
                ('direction_fr', models.CharField(default='DIRECTION GÉNÉRALE DES IMPÔTS', max_length=300, verbose_name='Direction (FR)')),
                ('programme_fr', models.CharField(default='PROGRAMME DE SÉCURISATION DES RECETTES ROUTIÈRES', max_length=300, verbose_name='Programme (FR)')),
                ('republique_en', models.CharField(default='REPUBLIC OF CAMEROON', max_length=200, verbose_name='République (EN)')),
                ('devise_en', models.CharField(default='Peace-Work-Fatherland', max_length=200, verbose_name='Devise (EN)')),
                ('ministere_en', models.CharField(default='MINISTRY OF FINANCE', max_length=300, verbose_name='Ministère (EN)')),
                ('direction_en', models.CharField(default='GENERAL DIRECTORATE OF TAXATION', max_length=300, verbose_name='Direction (EN)')),
                ('programme_en', models.CharField(default='REGIONAL TAXATION CENTER', max_length=300, verbose_name='Programme (EN)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration globale',
                'verbose_name_plural': 'Configuration globale',
            },
        ),
        migrations.DeleteModel(
            name='ConfigurationPoste',
        ),
    ]
