# Generated by Django 5.2.4 on 2025-10-07 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_poste_objectif_annuel'),
        ('inventaire', '0008_configurationglobale_delete_configurationposte'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquestock',
            name='numero_bordereau',
            field=models.CharField(blank=True, help_text='Généré automatiquement pour les transferts', max_length=50, null=True, verbose_name='Numéro de bordereau'),
        ),
        migrations.AddField(
            model_name='historiquestock',
            name='poste_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_entrants', to='accounts.poste', verbose_name='Poste de destination (transfert)'),
        ),
        migrations.AddField(
            model_name='historiquestock',
            name='poste_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_sortants', to='accounts.poste', verbose_name="Poste d'origine (transfert)"),
        ),
        migrations.AlterField(
            model_name='historiquestock',
            name='type_stock',
            field=models.CharField(blank=True, choices=[('regularisation', 'Régularisation'), ('imprimerie_nationale', 'Imprimerie Nationale'), ('reapprovisionnement', 'Réapprovisionnement Inter-Postes')], help_text="Type d'approvisionnement", max_length=30, null=True, verbose_name='Type de stock'),
        ),
    ]
