# Generated by Django 5.2.4 on 2025-08-18 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventaire', '0008_fix_configurationjour_final'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='configurationjour',
            name='unique_date_poste_configuration',
        ),
        migrations.RemoveConstraint(
            model_name='configurationjour',
            name='unique_date_global_configuration',
        ),
        migrations.RemoveIndex(
            model_name='configurationjour',
            name='inventaire_config_date_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='configurationjour',
            new_name='inventaire__poste_i_c1aa75_idx',
            old_name='inventaire_config_poste_date_idx',
        ),
        migrations.AddConstraint(
            model_name='configurationjour',
            constraint=models.UniqueConstraint(fields=('date', 'poste'), name='unique_date_poste_configuration'),
        ),
    ]
