# Generated by Django 5.2.4 on 2025-09-12 13:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventaire', '0009_remove_configurationjour_unique_date_poste_configuration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammationInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(help_text='Premier jour du mois concerné', verbose_name='Mois de programmation')),
                ('motif', models.CharField(choices=[('taux_deperdition', 'Taux de déperdition élevé'), ('risque_baisse', 'Risque de baisse annuel'), ('grand_stock', 'Risque de grand stock')], default=0, max_length=20, verbose_name="Motif de l'inventaire")),
                ('taux_deperdition_precedent', models.DecimalField(blank=True, decimal_places=2, help_text='Saisi manuellement ou récupéré du dernier inventaire', max_digits=6, null=True, verbose_name='Taux de déperdition précédent (%)')),
                ('risque_baisse_annuel', models.BooleanField(default=False, help_text='Calculé automatiquement selon les recettes', verbose_name='Risque de baisse annuel')),
                ('recettes_periode_actuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Recettes période actuelle')),
                ('recettes_periode_precedente', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Recettes même période année précédente')),
                ('stock_restant', models.IntegerField(blank=True, null=True, verbose_name='Stock restant de tickets')),
                ('date_epuisement_prevu', models.DateField(blank=True, null=True, verbose_name="Date d'épuisement prévue du stock")),
                ('risque_grand_stock', models.BooleanField(default=False, help_text="Si la date d'épuisement dépasse le 31 décembre", verbose_name='Risque de grand stock')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('actif', models.BooleanField(default=True, verbose_name='Programmation active')),
            ],
            options={
                'verbose_name': 'Programmation inventaire',
                'verbose_name_plural': 'Programmations inventaires',
                'ordering': ['-mois', 'poste__nom'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='posteinventairemensuel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='posteinventairemensuel',
            name='inventaire_mensuel',
        ),
        migrations.RemoveField(
            model_name='posteinventairemensuel',
            name='poste',
        ),
        migrations.RemoveConstraint(
            model_name='configurationjour',
            name='unique_date_poste_configuration',
        ),
        migrations.RemoveIndex(
            model_name='configurationjour',
            name='inventaire__poste_i_c1aa75_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventairejournalier',
            name='inventaire__verroui_98fd8d_idx',
        ),
        migrations.RemoveField(
            model_name='inventairejournalier',
            name='date_validation',
        ),
        migrations.RemoveField(
            model_name='inventairejournalier',
            name='valide',
        ),
        migrations.RemoveField(
            model_name='inventairejournalier',
            name='valide_par',
        ),
        migrations.RemoveField(
            model_name='inventairejournalier',
            name='verrouille',
        ),
        migrations.RemoveField(
            model_name='inventairemensuel',
            name='jours_actifs',
        ),
        migrations.RemoveField(
            model_name='recettejournaliere',
            name='valide',
        ),
        migrations.RemoveField(
            model_name='recettejournaliere',
            name='verrouille',
        ),
        migrations.AddField(
            model_name='configurationjour',
            name='type_config',
            field=models.CharField(choices=[('inventaire', 'Configuration Inventaire'), ('recette', 'Configuration Recette')], default='inventaire', max_length=15, verbose_name='Type de configuration'),
        ),
        migrations.AddField(
            model_name='inventairejournalier',
            name='derniere_modification_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Dernière modification par'),
        ),
        migrations.AddField(
            model_name='inventairejournalier',
            name='modifiable_par_agent',
            field=models.BooleanField(default=True, help_text='False après première soumission, seul admin peut modifier', verbose_name="Modifiable par l'agent"),
        ),
        migrations.AddField(
            model_name='inventairemensuel',
            name='date_epuisement_stock',
            field=models.DateField(blank=True, null=True, verbose_name="Date prévue d'épuisement du stock"),
        ),
        migrations.AddField(
            model_name='inventairemensuel',
            name='motif',
            field=models.CharField(choices=[('taux_deperdition', 'Taux de déperdition élevé'), ('risque_baisse', 'Risque de baisse annuel'), ('grand_stock', 'Risque de grand stock')], default='taux_deperdition', max_length=20, verbose_name="Motif de l'inventaire"),
        ),
        migrations.AddField(
            model_name='inventairemensuel',
            name='nombre_jours_impertinents',
            field=models.IntegerField(default=0, verbose_name='Nombre de jours impertinents'),
        ),
        migrations.AddField(
            model_name='inventairemensuel',
            name='nombre_jours_saisis',
            field=models.IntegerField(default=0, verbose_name='Nombre de jours saisis'),
        ),
        migrations.AddField(
            model_name='inventairemensuel',
            name='poste',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inventaires_mensuels', to='accounts.poste', verbose_name='Poste'),
        ),
        migrations.AddField(
            model_name='inventairemensuel',
            name='risque_baisse_annuel',
            field=models.BooleanField(default=False, verbose_name='Risque de baisse annuel détecté'),
        ),
        migrations.AddField(
            model_name='inventairemensuel',
            name='taux_deperdition_moyen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Taux de déperdition moyen (%)'),
        ),
        migrations.AddField(
            model_name='inventairemensuel',
            name='taux_deperdition_precedent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Taux de déperdition précédent (%)'),
        ),
        migrations.AddField(
            model_name='inventairemensuel',
            name='total_recettes_declarees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Total recettes déclarées'),
        ),
        migrations.AddField(
            model_name='inventairemensuel',
            name='total_recettes_potentielles',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Total recettes potentielles'),
        ),
        migrations.AddField(
            model_name='inventairemensuel',
            name='total_vehicules',
            field=models.IntegerField(default=0, verbose_name='Total véhicules du mois'),
        ),
        migrations.AddField(
            model_name='recettejournaliere',
            name='derniere_modification_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recettes_modifiees', to=settings.AUTH_USER_MODEL, verbose_name='Dernière modification par'),
        ),
        migrations.AddField(
            model_name='recettejournaliere',
            name='modifiable_par_chef',
            field=models.BooleanField(default=True, help_text='False après première soumission, seul admin peut modifier', verbose_name='Modifiable par le chef'),
        ),
        migrations.AddField(
            model_name='recettejournaliere',
            name='stock_tickets_restant',
            field=models.IntegerField(blank=True, help_text='Nombre de tickets restants après cette journée', null=True, verbose_name='Stock de tickets restant'),
        ),
        migrations.AlterField(
            model_name='configurationjour',
            name='commentaire',
            field=models.TextField(blank=True, help_text='Raison du marquage ou notes particulières', verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='configurationjour',
            name='date',
            field=models.DateField(help_text='Date concernée par cette configuration', unique=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='configurationjour',
            name='statut',
            field=models.CharField(choices=[('impertinent', 'Journée impertinente'), ('normal', 'Journée normale')], default='normal', max_length=15, verbose_name='Statut du jour'),
        ),
        migrations.AddField(
            model_name='programmationinventaire',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmations_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='programmationinventaire',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmations_inventaire', to='accounts.poste', verbose_name='Poste'),
        ),
        migrations.AddField(
            model_name='inventairemensuel',
            name='programmation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaire_mensuel', to='inventaire.programmationinventaire', verbose_name='Programmation associée'),
        ),
        migrations.DeleteModel(
            name='PosteInventaireMensuel',
        ),
        migrations.AddIndex(
            model_name='programmationinventaire',
            index=models.Index(fields=['poste', '-mois'], name='inventaire__poste_i_f75cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='programmationinventaire',
            index=models.Index(fields=['motif'], name='inventaire__motif_0f47ad_idx'),
        ),
        migrations.AddIndex(
            model_name='programmationinventaire',
            index=models.Index(fields=['actif'], name='inventaire__actif_21e021_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programmationinventaire',
            unique_together={('poste', 'mois')},
        ),
    ]
