# Generated by Django 5.2.4 on 2025-10-09 09:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_poste_objectif_annuel'),
        ('inventaire', '0009_historiquestock_numero_bordereau_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date début passage')),
                ('date_fin', models.DateField(verbose_name='Date fin passage')),
                ('taux_moyen_avant', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Taux moyen avant (%)')),
                ('date_stock_avant', models.DateField(blank=True, null=True, verbose_name='Date stock avant')),
                ('recettes_mois_avant', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Recettes mois avant')),
                ('taux_moyen_apres', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Taux moyen après (%)')),
                ('date_stock_apres', models.DateField(blank=True, null=True, verbose_name='Date stock après')),
                ('recettes_mois_apres', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Recettes mois après')),
                ('note_stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, verbose_name='Note stock /20')),
                ('note_recettes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, verbose_name='Note recettes /20')),
                ('note_taux', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, verbose_name='Note taux /20')),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, verbose_name='Note moyenne /20')),
                ('nombre_jours_impertinents', models.IntegerField(default=0, verbose_name='Jours impertinents')),
                ('date_calcul', models.DateTimeField(auto_now=True, verbose_name='Date calcul')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances_agent', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances_agents', to='accounts.poste', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Performance agent',
                'verbose_name_plural': 'Performances agents',
                'ordering': ['-note_moyenne', 'agent__nom_complet'],
                'unique_together': {('agent', 'poste', 'date_debut')},
            },
        ),
        migrations.CreateModel(
            name='PerformancePoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début période')),
                ('date_fin', models.DateField(verbose_name='Date de fin période')),
                ('motifs', models.JSONField(default=list, help_text='Liste des motifs sur la période', verbose_name='Motifs identifiés')),
                ('taux_moyen_deperdition', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Taux moyen déperdition (%)')),
                ('taux_plus_bas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Taux le plus bas (%)')),
                ('taux_plus_eleve', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Taux le plus élevé (%)')),
                ('date_epuisement_debut', models.DateField(blank=True, null=True, verbose_name='Date épuisement début')),
                ('date_epuisement_fin', models.DateField(blank=True, null=True, verbose_name='Date épuisement fin')),
                ('evolution_stock_jours', models.IntegerField(default=0, help_text='Positif = rapproché, Négatif = éloigné', verbose_name='Évolution stock (jours)')),
                ('recettes_periode', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Recettes période')),
                ('recettes_periode_precedente', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Recettes période précédente')),
                ('taux_evolution_recettes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Taux évolution recettes (%)')),
                ('nombre_jours_impertinents', models.IntegerField(default=0, verbose_name='Nombre jours impertinents')),
                ('date_calcul', models.DateTimeField(auto_now=True, verbose_name='Date du calcul')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='accounts.poste', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Performance poste',
                'verbose_name_plural': 'Performances postes',
                'ordering': ['-date_debut', 'poste__nom'],
                'unique_together': {('poste', 'date_debut', 'date_fin')},
            },
        ),
    ]
