# Generated by Django 5.2.4 on 2025-09-12 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventaire', '0010_programmationinventaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventairemensuel',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventaires_mensuels', to='accounts.poste', verbose_name='Poste'),
        ),
    ]
