# Generated by Django 5.2.4 on 2025-10-09 15:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_poste_objectif_annuel'),
        ('inventaire', '0010_performanceagent_performanceposte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificationEcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date début période')),
                ('date_fin', models.DateField(verbose_name='Date fin période')),
                ('montant_quittance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant total quittancé')),
                ('montant_declare', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant total déclaré')),
                ('ecart', models.DecimalField(decimal_places=2, help_text='Quittancé - Déclaré', max_digits=15, verbose_name='Écart')),
                ('justification', models.TextField(help_text="Explication détaillée de l'écart constaté", verbose_name="Justification de l'écart")),
                ('date_justification', models.DateTimeField(auto_now_add=True, verbose_name='Date de justification')),
                ('justifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Justifié par')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications_ecart', to='accounts.poste', verbose_name='Poste')),
            ],
            options={
                'verbose_name': "Justification d'écart",
                'verbose_name_plural': "Justifications d'écarts",
                'ordering': ['-date_justification'],
                'unique_together': {('poste', 'date_debut', 'date_fin')},
            },
        ),
        migrations.CreateModel(
            name='Quittancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_quittance', models.CharField(help_text='Numéro unique de la quittance', max_length=50, unique=True, verbose_name='Numéro de quittance')),
                ('exercice', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2099)], verbose_name='Exercice (Année)')),
                ('type_declaration', models.CharField(choices=[('jour', 'Par Jour'), ('decade', 'Par Décade')], default='jour', max_length=10, verbose_name='Type de déclaration')),
                ('date_quittancement', models.DateField(help_text='Date du jour du quittancement', verbose_name='Date de quittancement')),
                ('date_recette', models.DateField(blank=True, help_text='Si type = JOUR', null=True, verbose_name='Date de la recette')),
                ('date_debut_decade', models.DateField(blank=True, help_text='Si type = DECADE', null=True, verbose_name='Date début décade')),
                ('date_fin_decade', models.DateField(blank=True, help_text='Si type = DECADE', null=True, verbose_name='Date fin décade')),
                ('poste_comptable', models.CharField(help_text='Code alphanumérique du poste comptable', max_length=50, verbose_name='Poste comptable')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant quittancé (FCFA)')),
                ('image_quittance', models.ImageField(help_text='Scan ou photo de la quittance', upload_to='quittances/%Y/%m/', verbose_name='Image de la quittance')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('verrouille', models.BooleanField(default=True, help_text='Les quittancements sont verrouillés dès leur création', verbose_name='Verrouillé')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quittancements', to='accounts.poste', verbose_name='Poste')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quittancements_saisis', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
            ],
            options={
                'verbose_name': 'Quittancement',
                'verbose_name_plural': 'Quittancements',
                'ordering': ['-date_quittancement', 'poste__nom'],
                'indexes': [models.Index(fields=['poste', 'exercice'], name='inventaire__poste_i_e0b999_idx'), models.Index(fields=['numero_quittance'], name='inventaire__numero__59c280_idx'), models.Index(fields=['date_quittancement'], name='inventaire__date_qu_bb92ea_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('type_declaration', 'jour')), fields=('poste', 'date_quittancement', 'date_recette'), name='unique_quittancement_jour')],
            },
        ),
    ]
