# Generated by Django 5.2.4 on 2025-09-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventaire', '0011_alter_inventairemensuel_poste'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmationinventaire',
            options={'ordering': ['-mois', 'poste__nom', 'motif'], 'verbose_name': 'Programmation inventaire', 'verbose_name_plural': 'Programmations inventaires'},
        ),
        migrations.AlterUniqueTogether(
            name='programmationinventaire',
            unique_together={('poste', 'mois', 'motif')},
        ),
        migrations.AddField(
            model_name='programmationinventaire',
            name='pourcentage_baisse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Pourcentage de baisse (%)'),
        ),
    ]
