# Generated by Django 5.2.4 on 2025-10-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0011_justificationecart_quittancement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quittancement',
            name='poste_comptable',
        ),
    ]
