# Generated by Django 5.2.4 on 2025-10-11 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_poste_objectif_annuel'),
        ('inventaire', '0012_remove_quittancement_poste_comptable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quittancement',
            name='unique_quittancement_jour',
        ),
        migrations.AddField(
            model_name='quittancement',
            name='mois',
            field=models.CharField(blank=True, help_text='Format: YYYY-MM', max_length=7, verbose_name='Mois concerné'),
        ),
        migrations.AddField(
            model_name='quittancement',
            name='observations',
            field=models.TextField(blank=True, help_text='Observations optionnelles', verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='quittancement',
            name='image_quittance',
            field=models.ImageField(blank=True, help_text='Scan ou photo de la quittance', null=True, upload_to='quittances/%Y/%m/', verbose_name='Image de la quittance'),
        ),
        migrations.AddIndex(
            model_name='quittancement',
            index=models.Index(fields=['poste', 'mois'], name='inventaire__poste_i_aec2ca_idx'),
        ),
    ]
