# Generated by Django 5.2.4 on 2025-10-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0013_remove_quittancement_unique_quittancement_jour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quittancement',
            name='type_declaration',
            field=models.CharField(choices=[('journaliere', 'Journalière (Par Jour)'), ('decade', 'Par Décade')], default='journaliere', max_length=15, verbose_name='Type de déclaration'),
        ),
    ]
