# Generated by Django 5.2.4 on 2025-11-02 02:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_poste_objectif_annuel'),
        ('inventaire', '0014_alter_quittancement_type_declaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouleurTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_normalise', models.CharField(help_text='Code avec underscores (ex: bleu_clair)', max_length=50, unique=True, verbose_name='Code normalisé')),
                ('libelle_affichage', models.CharField(help_text='Libellé original saisi (ex: Bleu Clair)', max_length=50, verbose_name="Libellé d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Couleur de ticket',
                'verbose_name_plural': 'Couleurs de tickets',
                'ordering': ['code_normalise'],
            },
        ),
        migrations.CreateModel(
            name='DetailVenteTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_premier', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Premier ticket vendu')),
                ('numero_dernier', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dernier ticket vendu')),
                ('nombre_tickets', models.IntegerField(verbose_name='Nombre de tickets vendus')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('ordre', models.IntegerField(default=1, help_text="Pour conserver l'ordre de saisie des séries", verbose_name='Ordre de saisie')),
                ('couleur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventaire.couleurticket', verbose_name='Couleur')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_ventes_tickets', to='inventaire.recettejournaliere', verbose_name='Recette')),
            ],
            options={
                'verbose_name': 'Détail vente tickets',
                'verbose_name_plural': 'Détails ventes tickets',
                'ordering': ['recette', 'ordre'],
                'indexes': [models.Index(fields=['recette', 'ordre'], name='inventaire__recette_86ef51_idx')],
            },
        ),
        migrations.CreateModel(
            name='SerieTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_premier', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Numéro du premier ticket')),
                ('numero_dernier', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Numéro du dernier ticket')),
                ('nombre_tickets', models.IntegerField(help_text='Calculé automatiquement', verbose_name='Nombre de tickets')),
                ('valeur_monetaire', models.DecimalField(decimal_places=2, help_text='Calculée automatiquement : nombre_tickets * 500', max_digits=12, verbose_name='Valeur monétaire (FCFA)')),
                ('statut', models.CharField(choices=[('stock', 'En stock'), ('vendu', 'Vendu'), ('transfere', 'Transféré')], default='stock', max_length=20, verbose_name='Statut')),
                ('type_entree', models.CharField(blank=True, choices=[('imprimerie_nationale', 'Imprimerie Nationale'), ('regularisation', 'Régularisation'), ('transfert_recu', 'Transfert reçu')], max_length=30, null=True, verbose_name="Type d'entrée")),
                ('date_reception', models.DateTimeField(auto_now_add=True, verbose_name='Date de réception')),
                ('date_utilisation', models.DateField(blank=True, null=True, verbose_name="Date d'utilisation/vente")),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('couleur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='inventaire.couleurticket', verbose_name='Couleur')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_tickets', to='accounts.poste', verbose_name='Poste')),
                ('poste_destination_transfert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_tickets_recues', to='accounts.poste', verbose_name='Poste de destination (si transféré)')),
                ('reference_recette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_tickets_utilisees', to='inventaire.recettejournaliere', verbose_name='Recette associée')),
            ],
            options={
                'verbose_name': 'Série de tickets',
                'verbose_name_plural': 'Séries de tickets',
                'ordering': ['-date_reception', 'couleur', 'numero_premier'],
                'indexes': [models.Index(fields=['poste', 'statut'], name='inventaire__poste_i_c628e9_idx'), models.Index(fields=['couleur', 'statut'], name='inventaire__couleur_d41cc8_idx'), models.Index(fields=['statut', 'date_reception'], name='inventaire__statut_32dca3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('numero_premier__lte', models.F('numero_dernier'))), name='numero_premier_inferieur_dernier')],
            },
        ),
    ]
