# Generated by Django 5.2.4 on 2025-11-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0015_couleurticket_detailventeticket_serieticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquestock',
            name='series_tickets_associees',
            field=models.ManyToManyField(blank=True, help_text='Séries de tickets concernées par ce mouvement', related_name='historiques', to='inventaire.serieticket', verbose_name='Séries de tickets associées'),
        ),
    ]
