# Generated by Django 5.2.4 on 2025-11-05 12:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_poste_objectif_annuel'),
        ('inventaire', '0016_historiquestock_series_tickets_associees'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_snapshot', models.DateField(help_text='Date pour laquelle cette photo du stock est prise', verbose_name='Date du snapshot')),
                ('quantite_totale', models.IntegerField(default=0, verbose_name='Quantité totale de tickets')),
                ('valeur_totale', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Valeur totale (FCFA)')),
                ('series_json', models.JSONField(default=dict, help_text='Liste des séries présentes avec numéros et quantités', verbose_name='Détail des séries')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création du snapshot')),
                ('couleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='inventaire.couleurticket', verbose_name='Couleur')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_stock', to='accounts.poste', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Snapshot du stock',
                'verbose_name_plural': 'Snapshots du stock',
                'ordering': ['-date_snapshot', 'poste', 'couleur'],
                'indexes': [models.Index(fields=['poste', '-date_snapshot'], name='inventaire__poste_i_d28e9f_idx'), models.Index(fields=['date_snapshot'], name='inventaire__date_sn_7ca778_idx')],
                'unique_together': {('poste', 'date_snapshot', 'couleur')},
            },
        ),
    ]
