# Generated by Django 5.2.4 on 2025-11-05 12:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_poste_objectif_annuel'),
        ('inventaire', '0017_snapshotstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotStockJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_snapshot', models.DateField(help_text='Date à laquelle le stock a été capturé', verbose_name='Date du snapshot')),
                ('stock_total_quantite', models.IntegerField(default=0, verbose_name='Quantité totale en stock')),
                ('stock_total_valeur', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Valeur totale du stock (FCFA)')),
                ('details_par_couleur', models.JSONField(default=dict, help_text='Structure: {couleur: {series: [...], total_tickets: X, valeur: Y}}', verbose_name='Détails du stock par couleur')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création du snapshot')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_stock', to='accounts.poste', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Snapshot Stock Journalier',
                'verbose_name_plural': 'Snapshots Stock Journaliers',
                'ordering': ['-date_snapshot', 'poste__nom'],
            },
        ),
        migrations.DeleteModel(
            name='SnapshotStock',
        ),
        migrations.AddIndex(
            model_name='snapshotstockjournalier',
            index=models.Index(fields=['poste', '-date_snapshot'], name='inventaire__poste_i_406e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshotstockjournalier',
            index=models.Index(fields=['date_snapshot'], name='inventaire__date_sn_6bc350_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='snapshotstockjournalier',
            unique_together={('poste', 'date_snapshot')},
        ),
    ]
