# Generated by Django 5.2.4 on 2025-11-06 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_poste_objectif_annuel'),
        ('inventaire', '0018_snapshotstockjournalier_delete_snapshotstock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INITIAL', 'Stock Initial'), ('CHARGEMENT', 'Chargement de Stock'), ('VENTE', 'Vente de Tickets'), ('TRANSFERT_IN', 'Transfert Entrant'), ('TRANSFERT_OUT', 'Transfert Sortant'), ('AJUSTEMENT', 'Ajustement Manuel'), ('REGULARISATION', 'Régularisation')], max_length=20, verbose_name="Type d'événement")),
                ('event_datetime', models.DateTimeField(db_index=True, verbose_name="Date et heure de l'événement")),
                ('montant_variation', models.DecimalField(decimal_places=2, help_text='Positif pour ajout, négatif pour retrait', max_digits=15, verbose_name='Variation du stock (+ ou -)')),
                ('nombre_tickets_variation', models.IntegerField(help_text='Positif pour ajout, négatif pour retrait', verbose_name='Variation en nombre de tickets')),
                ('stock_resultant', models.DecimalField(decimal_places=2, help_text='Valeur du stock après application de cet événement', max_digits=15, verbose_name="Stock après l'événement")),
                ('tickets_resultants', models.IntegerField(verbose_name="Nombre de tickets après l'événement")),
                ('reference_id', models.CharField(blank=True, help_text='ID de la recette, transfert, etc.', max_length=100, verbose_name='ID de référence')),
                ('reference_type', models.CharField(blank=True, help_text='RecetteJournaliere, HistoriqueStock, etc.', max_length=50, verbose_name='Type de référence')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données additionnelles (séries, couleurs, etc.)', verbose_name='Métadonnées')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Événement annulé')),
                ('cancellation_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_by', to='inventaire.stockevent', verbose_name="Annulé par l'événement")),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_events', to='accounts.poste', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Événement de stock',
                'verbose_name_plural': 'Événements de stock',
                'ordering': ['poste', 'event_datetime'],
            },
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='Date du snapshot')),
                ('valeur_stock', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valeur du stock')),
                ('nombre_tickets', models.IntegerField(verbose_name='Nombre de tickets')),
                ('nombre_events', models.IntegerField(verbose_name="Nombre d'événements inclus")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_snapshots', to='accounts.poste', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Snapshot de stock',
                'verbose_name_plural': 'Snapshots de stock',
                'ordering': ['poste', '-snapshot_date'],
            },
        ),
        migrations.DeleteModel(
            name='SnapshotStockJournalier',
        ),
        migrations.AddIndex(
            model_name='stockevent',
            index=models.Index(fields=['poste', 'event_datetime'], name='inventaire__poste_i_63403f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockevent',
            index=models.Index(fields=['poste', '-event_datetime'], name='inventaire__poste_i_89f706_idx'),
        ),
        migrations.AddIndex(
            model_name='stockevent',
            index=models.Index(fields=['event_type'], name='inventaire__event_t_0454d8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockevent',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventaire__referen_f470fd_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['poste', '-snapshot_date'], name='inventaire__poste_i_51bfc2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocksnapshot',
            unique_together={('poste', 'snapshot_date')},
        ),
    ]
