# Generated by Django 5.2.4 on 2025-11-09 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0019_stockevent_stocksnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serieticket',
            name='responsable_reception',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a réceptionné cette série', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_receptionnees', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de la réception'),
        ),
    ]
