# Generated by Django 5.2.4 on 2025-11-10 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0020_serieticket_responsable_reception'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquestock',
            name='couleur_principale',
            field=models.ForeignKey(blank=True, help_text='Couleur des tickets (pour approvisionnement)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_couleur', to='inventaire.couleurticket', verbose_name='Couleur principale'),
        ),
        migrations.AddField(
            model_name='historiquestock',
            name='details_approvisionnement',
            field=models.JSONField(blank=True, default=dict, help_text="Détails structurés de l'approvisionnement (séries multiples, etc.)", verbose_name="Détails de l'approvisionnement"),
        ),
        migrations.AddField(
            model_name='historiquestock',
            name='numero_dernier_ticket',
            field=models.IntegerField(blank=True, help_text='Dernier numéro de la série (pour approvisionnement)', null=True, verbose_name='Dernier numéro de ticket'),
        ),
        migrations.AddField(
            model_name='historiquestock',
            name='numero_premier_ticket',
            field=models.IntegerField(blank=True, help_text='Premier numéro de la série (pour approvisionnement)', null=True, verbose_name='Premier numéro de ticket'),
        ),
    ]
