# Generated by Django 5.2.4 on 2025-11-13 11:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_poste_nouveau'),
        ('inventaire', '0021_historiquestock_couleur_principale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatInventaireSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_snapshot', models.DateField(db_index=True, verbose_name='Date du snapshot')),
                ('taux_deperdition', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Taux de déperdition (%)')),
                ('risque_baisse_annuel', models.BooleanField(default=False, verbose_name='En risque de baisse annuel')),
                ('recettes_periode_actuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Recettes cumulées période actuelle')),
                ('recettes_periode_n1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Recettes même période N-1')),
                ('pourcentage_evolution', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Pourcentage d'évolution (%)")),
                ('stock_valeur', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Valeur du stock (FCFA)')),
                ('stock_tickets', models.IntegerField(default=0, verbose_name='Nombre de tickets en stock')),
                ('date_epuisement_prevu', models.DateField(blank=True, null=True, verbose_name="Date d'épuisement prévue du stock")),
                ('risque_grand_stock', models.BooleanField(default=False, help_text='Stock qui dépasse le 31 décembre', verbose_name='Risque de grand stock')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées additionnelles')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_inventaire', to='accounts.poste', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Snapshot état inventaire',
                'verbose_name_plural': 'Snapshots états inventaires',
                'ordering': ['poste', '-date_snapshot'],
                'indexes': [models.Index(fields=['poste', '-date_snapshot'], name='inventaire__poste_i_901797_idx'), models.Index(fields=['date_snapshot'], name='inventaire__date_sn_e62d52_idx'), models.Index(fields=['risque_baisse_annuel'], name='inventaire__risque__925837_idx'), models.Index(fields=['risque_grand_stock'], name='inventaire__risque__18cffd_idx')],
                'unique_together': {('poste', 'date_snapshot')},
            },
        ),
        migrations.CreateModel(
            name='JourneeImpertinente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date de la journée impertinente')),
                ('recette_declaree', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Recette déclarée')),
                ('recette_potentielle', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Recette potentielle')),
                ('ecart', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Écart')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journees_impertinentes', to='accounts.poste', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Journée impertinente',
                'verbose_name_plural': 'Journées impertinentes',
                'ordering': ['-date', 'poste__nom'],
                'indexes': [models.Index(fields=['poste', '-date'], name='inventaire__poste_i_10a5f9_idx'), models.Index(fields=['date'], name='inventaire__date_553af9_idx')],
                'unique_together': {('poste', 'date')},
            },
        ),
    ]
