# Generated by Django 5.2.4 on 2025-11-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0022_etatinventairesnapshot_journeeimpertinente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmationinventaire',
            name='taux_deperdition_precedent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saisi manuellement ou récupéré du dernier inventaire', max_digits=10, null=True, verbose_name='Taux de déperdition précédent (%)'),
        ),
    ]
