# Generated by Django 5.2.4 on 2025-11-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0023_alter_programmationinventaire_taux_deperdition_precedent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etatinventairesnapshot',
            name='taux_deperdition',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taux de déperdition (%)'),
        ),
        migrations.AlterField(
            model_name='inventairemensuel',
            name='taux_deperdition_moyen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taux de déperdition moyen (%)'),
        ),
        migrations.AlterField(
            model_name='inventairemensuel',
            name='taux_deperdition_precedent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taux de déperdition précédent (%)'),
        ),
        migrations.AlterField(
            model_name='recettejournaliere',
            name='taux_deperdition',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taux de déperdition calculé', max_digits=10, null=True, verbose_name='Taux de déperdition (%)'),
        ),
        migrations.AlterField(
            model_name='statistiquesperiodiques',
            name='taux_deperdition_moyen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taux de déperdition moyen (%)'),
        ),
    ]
