# Generated by Django 5.2.4 on 2025-12-05 20:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_poste_nouveau'),
        ('inventaire', '0024_alter_etatinventairesnapshot_taux_deperdition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmendeEmise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(help_text="Numéro unique de l'ordre de paiement", max_length=50, unique=True, verbose_name='Numéro du ticket')),
                ('immatriculation', models.CharField(help_text="Plaque d'immatriculation du véhicule", max_length=20, verbose_name='Immatriculation')),
                ('transporteur', models.CharField(help_text='Nom du transporteur ou de la société', max_length=100, verbose_name='Transporteur')),
                ('provenance', models.CharField(help_text='Ville de départ', max_length=100, verbose_name='Provenance')),
                ('destination', models.CharField(help_text='Ville de destination', max_length=100, verbose_name='Destination')),
                ('produit_transporte', models.CharField(help_text='Nature de la marchandise', max_length=100, verbose_name='Produit transporté')),
                ('operateur', models.CharField(help_text="Nom de l'opérateur/conducteur", max_length=100, verbose_name='Opérateur')),
                ('est_surcharge', models.BooleanField(default=False, help_text='Cocher si infraction pour surcharge', verbose_name='Surcharge')),
                ('est_hors_gabarit', models.BooleanField(default=False, help_text='Cocher si infraction pour hors gabarit', verbose_name='Hors Gabarit')),
                ('montant_amende', models.DecimalField(decimal_places=2, help_text='Montant total de la pénalité', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Montant de l'amende (FCFA)")),
                ('statut', models.CharField(choices=[('non_paye', 'Non Payé'), ('paye', 'Payé')], default='non_paye', max_length=15, verbose_name='Statut du paiement')),
                ('date_heure_emission', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date et heure d'émission")),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('observations', models.TextField(blank=True, help_text='Notes ou commentaires supplémentaires', verbose_name='Observations')),
                ('saisi_par', models.ForeignKey(help_text="Chef d'équipe qui a saisi l'amende", on_delete=django.db.models.deletion.PROTECT, related_name='amendes_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
                ('station', models.ForeignKey(limit_choices_to={'type': 'pesage'}, on_delete=django.db.models.deletion.PROTECT, related_name='amendes_emises', to='accounts.poste', verbose_name='Station de pesage')),
                ('valide_par', models.ForeignKey(blank=True, help_text='Régisseur qui a validé le paiement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendes_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Amende émise',
                'verbose_name_plural': 'Amendes émises',
                'ordering': ['-date_heure_emission'],
            },
        ),
        migrations.CreateModel(
            name='AmendeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('EMISSION', "Émission de l'amende"), ('PAIEMENT', 'Paiement validé'), ('ANNULATION', 'Annulation')], max_length=20, verbose_name="Type d'événement")),
                ('event_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="Date/heure de l'événement")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Données additionnelles de l'événement", verbose_name='Métadonnées')),
                ('amende', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventaire.amendeemise', verbose_name='Amende')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
            ],
            options={
                'verbose_name': 'Événement amende',
                'verbose_name_plural': 'Événements amendes',
                'ordering': ['-event_datetime'],
            },
        ),
        migrations.CreateModel(
            name='PeseesJournalieres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date de la journée de pesage (9h à 9h)', verbose_name='Date')),
                ('nombre_pesees', models.PositiveIntegerField(help_text='Total des pesées effectuées', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Nombre de pesées')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('saisi_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesees_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
                ('station', models.ForeignKey(limit_choices_to={'type': 'pesage'}, on_delete=django.db.models.deletion.CASCADE, related_name='pesees_journalieres', to='accounts.poste', verbose_name='Station de pesage')),
            ],
            options={
                'verbose_name': 'Pesées journalières',
                'verbose_name_plural': 'Pesées journalières',
                'ordering': ['-date', 'station__nom'],
            },
        ),
        migrations.CreateModel(
            name='QuittancementPesage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_quittancement', models.CharField(choices=[('journalier', 'Journalier'), ('decade', 'Par Décade')], default='journalier', max_length=15, verbose_name='Type de quittancement')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(help_text='Même date que début pour quittancement journalier', verbose_name='Date de fin')),
                ('montant_quittance', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant quittancé (FCFA)')),
                ('montant_attendu', models.DecimalField(blank=True, decimal_places=2, help_text='Calculé automatiquement depuis les amendes payées', max_digits=15, null=True, verbose_name='Montant attendu (FCFA)')),
                ('ecart', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Écart (FCFA)')),
                ('numero_quittance', models.CharField(max_length=50, unique=True, verbose_name='Numéro de quittance')),
                ('image_quittance', models.ImageField(blank=True, null=True, upload_to='quittances_pesage/%Y/%m/', verbose_name='Image de la quittance')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('verrouille', models.BooleanField(default=True, help_text='Les quittancements sont verrouillés dès leur création', verbose_name='Verrouillé')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('saisi_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quittancements_pesage_saisis', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
                ('station', models.ForeignKey(limit_choices_to={'type': 'pesage'}, on_delete=django.db.models.deletion.CASCADE, related_name='quittancements_pesage', to='accounts.poste', verbose_name='Station de pesage')),
            ],
            options={
                'verbose_name': 'Quittancement pesage',
                'verbose_name_plural': 'Quittancements pesage',
                'ordering': ['-date_debut', 'station__nom'],
            },
        ),
        migrations.CreateModel(
            name='StatistiquesPesagePeriodique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_periode', models.CharField(choices=[('journalier', 'Journalier'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('annuel', 'Annuel')], max_length=15, verbose_name='Type de période')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('nombre_pesees', models.PositiveIntegerField(default=0, verbose_name='Nombre de pesées')),
                ('nombre_emissions', models.PositiveIntegerField(default=0, help_text='Surcharge + HG comptent double', verbose_name="Nombre d'émissions")),
                ('nombre_hors_gabarit', models.PositiveIntegerField(default=0, verbose_name='Nombre de hors gabarit')),
                ('montant_emis', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Montant total émis')),
                ('montant_recouvre', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Montant recouvré')),
                ('reste_a_recouvrer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Reste à recouvrer')),
                ('date_calcul', models.DateTimeField(auto_now=True, verbose_name='Date du calcul')),
                ('station', models.ForeignKey(limit_choices_to={'type': 'pesage'}, on_delete=django.db.models.deletion.CASCADE, related_name='statistiques_pesage', to='accounts.poste', verbose_name='Station de pesage')),
            ],
            options={
                'verbose_name': 'Statistiques pesage',
                'verbose_name_plural': 'Statistiques pesage',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddIndex(
            model_name='amendeemise',
            index=models.Index(fields=['station', '-date_heure_emission'], name='inventaire__station_54c242_idx'),
        ),
        migrations.AddIndex(
            model_name='amendeemise',
            index=models.Index(fields=['numero_ticket'], name='inventaire__numero__bbe9de_idx'),
        ),
        migrations.AddIndex(
            model_name='amendeemise',
            index=models.Index(fields=['immatriculation'], name='inventaire__immatri_12b9da_idx'),
        ),
        migrations.AddIndex(
            model_name='amendeemise',
            index=models.Index(fields=['statut'], name='inventaire__statut_727a19_idx'),
        ),
        migrations.AddIndex(
            model_name='amendeemise',
            index=models.Index(fields=['date_heure_emission'], name='inventaire__date_he_37df1f_idx'),
        ),
        migrations.AddIndex(
            model_name='amendeevent',
            index=models.Index(fields=['amende', '-event_datetime'], name='inventaire__amende__7cf310_idx'),
        ),
        migrations.AddIndex(
            model_name='amendeevent',
            index=models.Index(fields=['event_type'], name='inventaire__event_t_20b7ce_idx'),
        ),
        migrations.AddIndex(
            model_name='peseesjournalieres',
            index=models.Index(fields=['station', '-date'], name='inventaire__station_761f6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='peseesjournalieres',
            unique_together={('station', 'date')},
        ),
        migrations.AddIndex(
            model_name='quittancementpesage',
            index=models.Index(fields=['station', '-date_debut'], name='inventaire__station_9d0036_idx'),
        ),
        migrations.AddIndex(
            model_name='quittancementpesage',
            index=models.Index(fields=['numero_quittance'], name='inventaire__numero__2bc5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='statistiquespesageperiodique',
            index=models.Index(fields=['station', 'type_periode', '-date_debut'], name='inventaire__station_91a6c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='statistiquespesageperiodique',
            unique_together={('station', 'type_periode', 'date_debut')},
        ),
    ]
