# Generated by Django 5.2.4 on 2025-12-07 16:48

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_utilisateursupper_habilitation'),
        ('inventaire', '0025_amendeemise_amendeevent_peseesjournalieres_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificationEcartPesage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date début période')),
                ('date_fin', models.DateField(verbose_name='Date fin période')),
                ('montant_quittance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant total quittancé')),
                ('montant_attendu', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant attendu (amendes payées)')),
                ('ecart', models.DecimalField(decimal_places=2, help_text='Quittancé - Attendu', max_digits=15, verbose_name='Écart')),
                ('justification', models.TextField(help_text="Explication détaillée de l'écart constaté (min. 20 caractères)", verbose_name="Justification de l'écart")),
                ('date_justification', models.DateTimeField(auto_now_add=True, verbose_name='Date de justification')),
            ],
            options={
                'verbose_name': "Justification d'écart pesage",
                'verbose_name_plural': "Justifications d'écarts pesage",
                'ordering': ['-date_justification'],
            },
        ),
        migrations.AlterModelOptions(
            name='quittancementpesage',
            options={'ordering': ['-date_quittancement', 'station__nom'], 'verbose_name': 'Quittancement pesage', 'verbose_name_plural': 'Quittancements pesage'},
        ),
        migrations.RemoveIndex(
            model_name='quittancementpesage',
            name='inventaire__station_9d0036_idx',
        ),
        migrations.RemoveField(
            model_name='quittancementpesage',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='quittancementpesage',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='quittancementpesage',
            name='type_quittancement',
        ),
        migrations.AddField(
            model_name='quittancementpesage',
            name='date_debut_decade',
            field=models.DateField(blank=True, help_text='Si type = DECADE', null=True, verbose_name='Date début décade'),
        ),
        migrations.AddField(
            model_name='quittancementpesage',
            name='date_fin_decade',
            field=models.DateField(blank=True, help_text='Si type = DECADE', null=True, verbose_name='Date fin décade'),
        ),
        migrations.AddField(
            model_name='quittancementpesage',
            name='date_quittancement',
            field=models.DateField(default=datetime.date(2025, 12, 7), help_text='Date du jour du quittancement', verbose_name='Date de quittancement'),
        ),
        migrations.AddField(
            model_name='quittancementpesage',
            name='date_recette',
            field=models.DateField(blank=True, help_text='Date des amendes payées (si type = JOURNALIERE)', null=True, verbose_name='Date des amendes'),
        ),
        migrations.AddField(
            model_name='quittancementpesage',
            name='exercice',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2099)], verbose_name='Exercice (Année)'),
        ),
        migrations.AddField(
            model_name='quittancementpesage',
            name='mois',
            field=models.CharField(blank=True, help_text='Format: YYYY-MM', max_length=7, verbose_name='Mois concerné'),
        ),
        migrations.AddField(
            model_name='quittancementpesage',
            name='type_declaration',
            field=models.CharField(choices=[('journaliere', 'Journalière (Par Jour)'), ('decade', 'Par Décade')], default='journaliere', max_length=15, verbose_name='Type de déclaration'),
        ),
        migrations.AlterField(
            model_name='quittancementpesage',
            name='ecart',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quittancé - Attendu', max_digits=12, null=True, verbose_name='Écart (FCFA)'),
        ),
        migrations.AlterField(
            model_name='quittancementpesage',
            name='image_quittance',
            field=models.ImageField(blank=True, help_text='Scan ou photo de la quittance', null=True, upload_to='quittances_pesage/%Y/%m/', verbose_name='Image de la quittance'),
        ),
        migrations.AlterField(
            model_name='quittancementpesage',
            name='montant_attendu',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculé depuis les amendes payées', max_digits=12, null=True, verbose_name='Montant attendu (FCFA)'),
        ),
        migrations.AlterField(
            model_name='quittancementpesage',
            name='montant_quittance',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant quittancé (FCFA)'),
        ),
        migrations.AlterField(
            model_name='quittancementpesage',
            name='numero_quittance',
            field=models.CharField(help_text='Numéro unique de la quittance', max_length=50, unique=True, verbose_name='Numéro de quittance'),
        ),
        migrations.AlterField(
            model_name='quittancementpesage',
            name='observations',
            field=models.TextField(blank=True, help_text='Observations optionnelles', verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='quittancementpesage',
            name='saisi_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quittancements_pesage_saisis', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par'),
        ),
        migrations.AlterField(
            model_name='quittancementpesage',
            name='station',
            field=models.ForeignKey(limit_choices_to={'type_poste': 'pesage'}, on_delete=django.db.models.deletion.CASCADE, related_name='quittancements_pesage', to='accounts.poste', verbose_name='Station de pesage'),
        ),
        migrations.AddIndex(
            model_name='quittancementpesage',
            index=models.Index(fields=['station', 'exercice'], name='inventaire__station_70a94e_idx'),
        ),
        migrations.AddIndex(
            model_name='quittancementpesage',
            index=models.Index(fields=['station', 'mois'], name='inventaire__station_8575fe_idx'),
        ),
        migrations.AddIndex(
            model_name='quittancementpesage',
            index=models.Index(fields=['date_quittancement'], name='inventaire__date_qu_004a85_idx'),
        ),
        migrations.AddIndex(
            model_name='quittancementpesage',
            index=models.Index(fields=['type_declaration'], name='inventaire__type_de_8fc6d6_idx'),
        ),
        migrations.AddField(
            model_name='justificationecartpesage',
            name='justifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_pesage_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Justifié par'),
        ),
        migrations.AddField(
            model_name='justificationecartpesage',
            name='station',
            field=models.ForeignKey(limit_choices_to={'type_poste': 'pesage'}, on_delete=django.db.models.deletion.CASCADE, related_name='justifications_ecart_pesage', to='accounts.poste', verbose_name='Station de pesage'),
        ),
        migrations.AddIndex(
            model_name='justificationecartpesage',
            index=models.Index(fields=['station', '-date_justification'], name='inventaire__station_c2edec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='justificationecartpesage',
            unique_together={('station', 'date_debut', 'date_fin')},
        ),
    ]
