# Generated by Django 5.2.4 on 2025-12-08 15:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_utilisateursupper_habilitation'),
        ('inventaire', '0026_justificationecartpesage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificationecartpesage',
            name='station',
            field=models.ForeignKey(limit_choices_to={'type': 'pesage'}, on_delete=django.db.models.deletion.CASCADE, related_name='justifications_ecart_pesage', to='accounts.poste', verbose_name='Station de pesage'),
        ),
        migrations.AlterField(
            model_name='quittancementpesage',
            name='date_quittancement',
            field=models.DateField(default=datetime.date(2025, 12, 8), help_text='Date du jour du quittancement', verbose_name='Date de quittancement'),
        ),
        migrations.AlterField(
            model_name='quittancementpesage',
            name='station',
            field=models.ForeignKey(limit_choices_to={'type': 'pesage'}, on_delete=django.db.models.deletion.CASCADE, related_name='quittancements_pesage', to='accounts.poste', verbose_name='Station de pesage'),
        ),
        migrations.CreateModel(
            name='DemandeConfirmationPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Référence unique de la demande (auto-générée)', max_length=50, unique=True, verbose_name='Référence')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de confirmation'), ('confirme', 'Confirmé - Paiement autorisé'), ('refuse', 'Refusé - Paiement bloqué'), ('expire', 'Expiré'), ('annule', 'Annulé par le demandeur')], default='en_attente', max_length=15, verbose_name='Statut')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('commentaire_demande', models.TextField(blank=True, help_text='Explication ou justification de la demande', verbose_name='Commentaire du demandeur')),
                ('commentaire_reponse', models.TextField(blank=True, help_text='Explication du régisseur confirmeur', verbose_name='Commentaire de réponse')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('date_expiration', models.DateTimeField(help_text='La demande expire automatiquement après cette date', verbose_name="Date d'expiration")),
                ('vehicule_immatriculation', models.CharField(help_text='Pour référence rapide', max_length=20, verbose_name='Immatriculation véhicule')),
                ('vehicule_transporteur', models.CharField(blank=True, max_length=100, verbose_name='Transporteur')),
                ('amende_a_valider', models.ForeignKey(help_text='Amende dont le paiement est en attente de confirmation', on_delete=django.db.models.deletion.CASCADE, related_name='demandes_confirmation_pour_validation', to='inventaire.amendeemise', verbose_name='Amende à valider')),
                ('amende_non_payee', models.ForeignKey(help_text='Amende non payée qui bloque la validation', on_delete=django.db.models.deletion.CASCADE, related_name='demandes_confirmation_bloquantes', to='inventaire.amendeemise', verbose_name='Amende non payée')),
                ('regisseur_confirmeur', models.ForeignKey(blank=True, help_text='Régisseur qui a traité la demande', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_confirmation_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Régisseur confirmeur')),
                ('regisseur_demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_confirmation_creees', to=settings.AUTH_USER_MODEL, verbose_name='Régisseur demandeur')),
                ('station_concernee', models.ForeignKey(help_text="Station où se trouve l'amende non payée", on_delete=django.db.models.deletion.CASCADE, related_name='demandes_confirmation_recues', to='accounts.poste', verbose_name='Station concernée')),
                ('station_demandeur', models.ForeignKey(help_text='Station qui demande la confirmation', on_delete=django.db.models.deletion.CASCADE, related_name='demandes_confirmation_envoyees', to='accounts.poste', verbose_name='Station demandeur')),
            ],
            options={
                'verbose_name': 'Demande de confirmation paiement',
                'verbose_name_plural': 'Demandes de confirmation paiement',
                'ordering': ['-date_demande'],
                'indexes': [models.Index(fields=['station_demandeur', '-date_demande'], name='inventaire__station_d51e48_idx'), models.Index(fields=['station_concernee', 'statut'], name='inventaire__station_89f267_idx'), models.Index(fields=['statut', '-date_demande'], name='inventaire__statut_b794cc_idx'), models.Index(fields=['reference'], name='inventaire__referen_f5bf0f_idx'), models.Index(fields=['vehicule_immatriculation'], name='inventaire__vehicul_381ffe_idx')],
            },
        ),
    ]
