# Generated by Django 5.2.4 on 2025-12-08 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_utilisateursupper_habilitation'),
        ('inventaire', '0027_alter_justificationecartpesage_station_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='amendeemise',
            name='immatriculation_normalise',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-généré pour recherche uniforme', max_length=20, verbose_name='Immatriculation normalisée'),
        ),
        migrations.AddField(
            model_name='amendeemise',
            name='operateur_normalise',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-généré pour recherche uniforme (chauffeur)', max_length=100, verbose_name='Opérateur normalisé'),
        ),
        migrations.AddField(
            model_name='amendeemise',
            name='transporteur_normalise',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-généré pour recherche uniforme', max_length=100, verbose_name='Transporteur normalisé'),
        ),
        migrations.AddIndex(
            model_name='amendeemise',
            index=models.Index(fields=['immatriculation_normalise'], name='inventaire__immatri_41aeeb_idx'),
        ),
        migrations.AddIndex(
            model_name='amendeemise',
            index=models.Index(fields=['transporteur_normalise'], name='inventaire__transpo_020998_idx'),
        ),
        migrations.AddIndex(
            model_name='amendeemise',
            index=models.Index(fields=['operateur_normalise'], name='inventaire__operate_daea79_idx'),
        ),
    ]
