# Generated by Django 5.2.4 on 2025-12-09 13:48

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_utilisateursupper_habilitation'),
        ('inventaire', '0028_amendeemise_immatriculation_normalise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quittancementpesage',
            name='date_quittancement',
            field=models.DateField(default=datetime.date(2025, 12, 9), help_text='Date du jour du quittancement', verbose_name='Date de quittancement'),
        ),
        migrations.CreateModel(
            name='ObjectifAnnuelPesage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2099)], verbose_name='Année')),
                ('montant_objectif', models.DecimalField(decimal_places=2, help_text="Objectif de recouvrement des amendes pour l'année", max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Objectif annuel (FCFA)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectifs_pesage_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('station', models.ForeignKey(limit_choices_to={'type': 'pesage'}, on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_annuels_pesage', to='accounts.poste', verbose_name='Station de pesage')),
            ],
            options={
                'verbose_name': 'Objectif annuel pesage',
                'verbose_name_plural': 'Objectifs annuels pesage',
                'ordering': ['-annee', 'station__nom'],
                'indexes': [models.Index(fields=['station', 'annee'], name='inventaire__station_4b53f5_idx'), models.Index(fields=['annee'], name='inventaire__annee_358d41_idx')],
                'unique_together': {('station', 'annee')},
            },
        ),
    ]
