# Generated by Django 5.2.4 on 2025-12-14 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0030_alter_quittancementpesage_date_quittancement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quittancementpesage',
            name='date_quittancement',
            field=models.DateField(default=datetime.date(2025, 12, 14), help_text='Date du jour du quittancement', verbose_name='Date de quittancement'),
        ),
    ]
