# Generated by Django 5.2.4 on 2025-12-27 11:53

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_utilisateursupper_date_personnalisation_and_more'),
        ('inventaire', '0031_alter_quittancementpesage_date_quittancement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quittancementpesage',
            name='date_quittancement',
            field=models.DateField(default=datetime.date(2025, 12, 27), help_text='Date du jour du quittancement', verbose_name='Date de quittancement'),
        ),
        migrations.AddIndex(
            model_name='serieticket',
            index=models.Index(fields=['couleur', 'date_reception', 'type_entree'], name='inventaire__couleur_1a3e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='serieticket',
            index=models.Index(fields=['numero_premier', 'numero_dernier'], name='inventaire__numero__82d00a_idx'),
        ),
    ]
